### PR TITLE
Add support for pushover devices

### PR DESCRIPTION
**Pull request by alec-pinson**
Extending [Pushover](https://pushover.net/) integration to allow for `device` parameter to be used.
https://pushover.net/api#device

### CODE REVIEW

**Comment by alec-pinson** [comment]
Hi, @simonpasquier @w0rm @gotjosh can one of you review this when you get chance please, it's a simple addition and I've tested it, thanks 😃.

**Review by simonpasquier — COMMENTED** [review]
Thanks for the PR! Could you also update the documentation in docs/configuration.md?
Am I correct in assuming that when `device` is empty then the notification is sent to all devices?

**Comment by alec-pinson** [comment]
> Thanks for the PR! Could you also update the documentation in docs/configuration.md? Am I correct in assuming that when `device` is empty then the notification is sent to all devices?

You are correct!
Sorry it took so long to update, I was away for a week.

**Review by gotjosh — APPROVED** [review]
LGTM

**Comment by gotjosh** [comment]
Anything else @simonpasquier ?

**Pull request merged**
