### PR TITLE
test: enable race detection

### PR DESCRIPTION
**Pull request by simonpasquier**
This change enables race detection when running the tests. It also fixes
a couple of existing race conditions.

Inspired by https://github.com/prometheus/prometheus/pull/3884 from @krasi-georgiev :smile:

### CODE REVIEW

**Comment by stuartnelson3** [comment]
awesome! will give this a look soon

**Comment by stuartnelson3** [comment]
awesome! will give this a look soon

**Comment by simonpasquier** [comment]
> I assume buffer (test/acceptance.go) was created so there is coordinated access writing to stdout and stderr
Exactly

**Comment by brancz** [comment]
:tada: :tada: :tada: Been wanting to do this for some time, thanks! :tada: :tada: :tada:

**Pull request merged**
