### PR TITLE
*: cut v0.8.0

### PR DESCRIPTION
**Pull request by mxinden**
* [FEATURE] Add ability to filter alerts by receiver in the UI (#890)
* [FEATURE] Add User-Agent for webhook requests (#893)
* [ENHANCEMENT] Add possibility to have a global victorops api_key (#897)
* [ENHANCEMENT] Add EntityDisplayName and improve StateMessage for Victorops
  (#769)
* [ENHANCEMENT] Omit empty config fields and show regex upon re-marshalling to
  elide secrets (#864)
* [ENHANCEMENT] Parse API error messages in UI (#866)
* [ENHANCEMENT] Enable sending mail via smtp port 465 (#704)
* [BUGFIX] Prevent duplicate notifications by sorting matchers (#882)
* [BUGFIX] Remove timeout for UI requests (#890)
* [BUGFIX] Update config file location of CLI in flag usage text (#895)

### CODE REVIEW

**Comment by stuartnelson3** [comment]
Something seems to be wrong with the receiver filtering:

image

image

image

This probably warrants investigation. Similar manual testing for the group_by auto complete seems to be functioning as expected.

**Comment by mxinden** [comment]
@stuartnelson3 thanks for the catch! Same on my machine. @w0rm Are you able to reproduce this?

**Comment by w0rm** [comment]
@mxinden @stuartnelson3 I'm using the same algorithm. In your example you wrote the last part of the word. It is the same in grouping:

screen shot 2017-07-16 at 22 05 21

**Comment by stuartnelson3** [comment]
Hm, so goofy:

image

One letter makes the difference.

I'll play with it tomorrow, there are some weighting numbers we can fiddle with. There's definitely something wrong that would be nice to fix before cutting another release.

**Comment by stuartnelson3** [comment]
I'm guessing `ance` bumps `severity` up to the top because they both have an `e` in the same place, which gets a good bump. Will try to weight for consecutive letters within a word, not just the initial words in a search.

the switch between `web.hook1` and `web.hook2` is something I can't explain ..

**Comment by mxinden** [comment]
Once #910 is merged I will rebase here.

**Comment by stuartnelson3** [comment]
Merged, once it's rebased you have my :+1:

**Comment by beorn7** [comment]
Yes, please rebase and adjust the release date.

I'm keen on finally deploying an officially released version at SC again. :)

**Comment by beorn7** [comment]
Superceeded by #915

**Pull request closed without merging**
