### PR TITLE
Extend inhibition test to check post-inhibition behavior.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
@fabxc Hmm, the last group of alerts between 5 and 5.5 don't arrive at all - am I overlooking something or should they arrive?

**Comment by fabxc** [comment]
In general, having several long tests touching many aspects at once is good. For the core behaviors we should have very small-scoped tests so we can see relatively precisely which aspects fail.

**Comment by fabxc** [comment]
Also I cannot reproduce. The test passes for me locally.

**Comment by juliusv** [comment]
I rebased and enlarged the expected intervals a bit (from x.5 to x.8), but still getting test failures about half of the time, but now the second batch is broken:

```
		collector "webhook":
		
		interval [4,4.8]
		---
		- test1[38692d7][active][1:]
		- InstanceDown[27b9fd8][active][1:]
		- InstanceDown[27b9fd8][active][1:]
		- JobDown[13c0540][resolved][2:4]
		  [ ✓ ]
		interval [5,5.8]
		---
		- test1[38692d7][active][1:]
		- InstanceDown[27b9fd8][active][1:]
		- InstanceDown[27b9fd8][active][1:]
		  [ ✓ ]
		interval [2,2.8]
		---
		- test1[38692d7][active][1:]
		- InstanceDown[27bbfd8][active][1:]
		- InstanceDown[27b9fd8][active][1:]
		  [ ✓ ]
		interval [3,3.8]
		---
		- test1[38692d7][active][1:]
		- InstanceDown[27b9fd8][active][1:]
		- JobDown[13c0540][resolved][2:4]
		  [ ✗ ]
		
		Expected total of 13 alerts, got 11
		received:
		@ 4.002062875
		- JobDown[13c0540][resolved][2:4]
		- InstanceDown[27b9fd8][active][1.001084501:]
		- InstanceDown[27bbfd8][active][1.001266521:]
		- test1[38692d7][active][1.001381771:]
		@ 5.002290578
		- InstanceDown[27b9fd8][active][1.001084501:]
		- InstanceDown[27bbfd8][active][1.001266521:]
		- test1[38692d7][active][1.001381771:]
		@ 2.003746429
		- InstanceDown[27b9fd8][active][1.001084501:]
		- InstanceDown[27bbfd8][active][1.001266521:]
		- test1[38692d7][active][1.001381771:]
		@ 3.001883657
		- JobDown[13c0540][resolved][2:4]
```

**Pull request closed without merging**
