### PR TITLE
cherry-pick bug fixes and cli patches into release-0.15

### PR DESCRIPTION
**Pull request by mxinden**
I have cherry-picked all bug fixes as well as all CLI related patches into the `release-0.15` branch. I would like to not include any breaking changes or new features between two release candidates. Thereby I have not included the following commits:

- b95b328 ui: replace deprecated InstrumentHandler() (#1302)
- f53b247 api: initialize alerts_received_total labels (#1310)
- 300a87e Removed file changes to resolve conflict. (#1318)
- bc263d3 Improve notification instrumentation (#1335)
- af5dd74 tell users opening issues to use alertmanager  --version (#1327)
- cecfe5b Validate Slack field config and only allow the necessary input (#1334)
- b04e9ad #1346: move maintenance messages to DEBUG log level (#1347)

The above mentioned patches will be included in the upcoming `v0.16.0` release.

Let me know what you think, whether I am missing something, or whether you disagree with this process proposal. I am happy to take care of the `v0.16.0` release in the upcoming weeks.

Version bump will follow in an upcoming PR.

### CODE REVIEW

**Comment by stuartnelson3** [comment]
I'm not sure what the implications are. I'm guessing we can just merge any commits that pre-date the adoption of the DCO, but since I'm not familiar with it I defer to @brian-brazil and @juliusv

**Comment by brian-brazil** [comment]
We can just go ahead here, there's no new code.

**Comment by mxinden** [comment]
Thanks @stuartnelson3 @brian-brazil.

I will merge once Prometheus operator e2e test suit succeeded: https://github.com/coreos/prometheus-operator/pull/1308

Should give us at least a pretty good K8s test coverage.

**Comment by mxinden** [comment]
@stuartnelson3 Prometheus operator test suit succeeded. Shall we move on with this PR, or wait for https://github.com/prometheus/alertmanager/issues/1341?

**Comment by mxinden** [comment]
Closing here in favour of https://github.com/prometheus/alertmanager/pull/1410.

**Pull request closed without merging**
