### PR TITLE
Add MS Teams webhook support

### PR DESCRIPTION
**Pull request by darkowlzz**
Refer: [Actionable Messages via Connectors](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-connectors)

screen shot 2017-10-04 at 1 02 59 am

The default theme color used for firing is #F35225 (Red in MS Logo), and resolved is #81BB05 (Green in MS Logo), to match with their theme, maybe 😄

Sample payload sent to Teams:
```json
{
  "@context": "http://schema.org/extensions",
  "@type": "MessageCard",
  "title": "Alert from System 7",
  "text": "[FIRING:1]  (TURTLE ALERT!!)",
  "themeColor": "F35225",
  "potentialAction": [
    {
      "@type": "OpenUri",
      "name": "View Alert",
      "targets": [
        {
          "os": "default",
          "uri": "http://localhost:9093/#/alerts?receiver=some-teams-rcvr"
        }
      ]
    }
  ]
}
```

Sample Alertmanager config for the same:
```yaml
global:
  teams_api_url: "https://outlook.office.com/webhook/somekey/IncomingWebhook/someotherkey"

receivers:
  - name: "some-teams-rcvr"
    teams_configs:
      - send_resolved: true
        # api_url: ""
        title: "Alert from System 7"
```

### CODE REVIEW

**Comment by sahilsk** [comment]
Let's get this merge. I was waiting for this integration. 🙏

**Comment by stuartnelson3** [comment]
thanks for the contribution!

unfortunately, as you can see in https://github.com/prometheus/docs/pull/843, we're currently not adding any new notifiers. Our recommendation is to implement additional integrations with the webhook notifier.

**Comment by sengaya** [comment]
I wonder if this PR could be reopened, now that recently [Telegram support](https://github.com/prometheus/alertmanager/pull/2827) was added and the [moratorium was lifted](https://github.com/prometheus/alertmanager/commit/1f3796c5cc58bdcf6fedfb427580c7bfab1f88ba).

**Comment by roidelapluie** [comment]
Probably not going to reopen, but feel free to work off the original commit and rebase it.

**Pull request closed without merging**
