### PR TITLE
allow global opsgenie api key

### LINKED ISSUE #1173: Default global api key for OpsGenie config
Can we default the OpsGenie `api_key` to be like `global.opsgenie_api_key` ? It looks like it's not configured like that looking at the docs on https://prometheus.io/docs/alerting/configuration/#opsgenie_config
```
# The API key to use when talking to the OpsGenie API.
api_key: <secret>
```

For example, the VictorOps config has 
```
# The API key to use when talking to the VictorOps API.
[ api_key: <secret> | default = global.victorops_api_key ]
```

### PR DESCRIPTION
**Pull request by caarlos0**
just like #897

closes #1173

### CODE REVIEW

**Comment by aioue** [comment]
worth commenting the route and receiver options, or adding a link to their description?

**Comment by caarlos0** [comment]
> worth commenting the route and receiver options, or adding a link to their description?

sorry, I didn't understand... can you elaborate please?

**Comment by caarlos0** [comment]
also added docs -> https://github.com/prometheus/docs/pull/955

**Comment by caarlos0** [comment]
thanks!

**Comment by caarlos0** [comment]
@stuartnelson3 FWIW the docs counterpart is pending merge https://github.com/prometheus/docs/pull/955

**Pull request merged**
