### PR TITLE
Add the receiver name to notification metrics

### PR DESCRIPTION
**Pull request by sinkingpoint**
Solves #3012 

This PR adds in a second label to all the *Notification* metrics, so that we not only have the type of notification, but all the receiver_name that the notification belongs to. 

Because of the proliferation of webhook notifiers (as recommended by the docs), this is necessary to be able to properly diagnose failures from metrics - currently we get one metric for all web hooks, regardless of the fact that they might represent completely different notification pathways.

This is technically a breaking change, so this might have to wait for a bigger release, if its even worthwhile at all

### CODE REVIEW

**Comment by roidelapluie** [comment]
Could we have this behind a cli flag?

Cli flag because I think we should issue it consistently over the lifetime of the app.

**Comment by sinkingpoint** [comment]
Sorry for the hiatus. Will push a CLI flag today

**Comment by sinkingpoint** [comment]
Fixed this up and it's ready for another review

**Comment by alimehrabikoshki** [comment]
@roidelapluie could you pls take another look?

**Comment by gotjosh** [comment]
Thank you very much for your contribution - you've been waiting for a long time on this so instead of dragging it back and forth, and went ahead and implemented a couple of suggestions I wanted on this PR.

The bulk of the change is around having the "feature flag management" on its package and applying a couple of patterns to keep them tidy for future additions.

The other big change is the fact that we can initialize ahead of time the metrics for the given receiver names. 

I'd love if @simonpasquier can take a look as I've written a big chunk of this code.

**Review by simonpasquier — COMMENTED** [review]
My main remark is that old label values would be retained after a config reload in case some receivers are deleted/renamed. I guess that we need [DeleteLabelValues()](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#MetricVec.DeleteLabelValues) to prune them.

**Comment by gotjosh** [comment]
> My main remark is that old label values would be retained after a config reload in case some receivers are deleted/renamed. I guess that we need [DeleteLabelValues()](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#MetricVec.DeleteLabelValues) to prune them.

I can't use `https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#MetricVec.DeleteLabelValues` as I would need to know the old label values to prune them (and I can, but this would be a pretty invasive change). Instead, I chose to use `Reset()` to prune all of the metrics in the given vector and then recreate them again - given all of these are counters this shouldn't be a problem, as they would simply go back to 0 and would count as counter reset anyways.

**Review by simonpasquier — APPROVED** [review]
LGTM

**Comment by gotjosh** [comment]
Thank you very much for your contribution @sinkingpoint.

**Comment by mmikitka-arcticwolf** [comment]
@gotjosh Do you have an estimate for when the next official Alertmanager container image will be available that includes this change?

**Comment by rtkwlf-nachiketrao** [comment]
@gotjosh Is there any update on when the new Alertmanager image will be available?

**Comment by gotjosh** [comment]
Have you tested out the current rc.0 https://github.com/prometheus/alertmanager/releases/tag/v0.27.0-rc.0? I'm planning on promoting the the RC to 27.0 by the end of the week if nothing major is reported.

**Pull request merged**
