### PR TITLE
[wip] introduce go mod

### PR DESCRIPTION
**Pull request by stuartnelson3**
This pr introduces the use of go modules.

There are still some things that need working on, for example how `GO111MODULE=on` is used everywhere to force the use of modules, since the code is most commonly run within `$GOPATH` where modules are currently opt-in.

`staticcheck` and `errcheck` also need to be revisited.

### CODE REVIEW

**Comment by simonpasquier** [comment]
`+245 −208,636` this is a drastic diet :slightly_smiling_face: I haven't had any significant experience with Go modules yet but I believe that `GO111MODULE=on` shouldn't be necessary if we move out of `GOPATH`. For CircleCI, it means removing the `working_directory` parameter (see https://circleci.com/blog/go-v1.11-modules-and-circleci/). But maybe you want it to work seamlessly for local dev?

> staticcheck and errcheck also need to be revisited.

Is that because `go get` modifies `mod.sum`?

Obviously changes to `Makefile.common` need to go to [prometheus/prometheus](https://github.com/prometheus/prometheus) first. We had similar discussions in https://github.com/prometheus/prombench/pull/161 as prombench already uses Go modules.

**Comment by stuartnelson3** [comment]
>Is that because go get modifies mod.sum?

It was failing because we ignore some imports in /vendor, but they aren't in /vendor anymore.

>Obviously changes to Makefile.common need to go to prometheus/prometheus first. We had similar discussions in prometheus/prombench#161 as prombench already uses Go modules.

That's cool, is this something you're interested in working on? You've been helping to keep the common parts in sync between the two projects :)

**Comment by simonpasquier** [comment]
Re prombench, @sipian said that he was going to be a bit offline for a couple of days. But sure, I'll do some homework on Go modules and try to understand what we need to get in `Makefile.common`.

**Comment by simonpasquier** [comment]
@stuartnelson3, quick heads-up. I'm looking into `go mod`'ing the Prometheus repository and tackle the necessary updates to `Makefile.common`. Also we chatted briefly about it with @brancz and he was more inclined to keep the `vendor/` directory with guarantees reproducible builds and protects us from version control systems being down.

**Comment by stuartnelson3** [comment]
@simonpasquier if you get a chance to push this forward now that the prometheus gomod pr is merged ... :)

**Comment by simonpasquier** [comment]
Yep it is on my list :smiley:

**Comment by simonpasquier** [comment]
Superseded by #1630

**Pull request closed without merging**
