### PR TITLE
Log whole request and response on notify error

### PR DESCRIPTION
**Pull request by BrentDouglas**
When operating alertmanager the existing logs provide no context as to
why a request is failing. Logging the whole request and response makes
debugging these issues significantly simpler.

### CODE REVIEW

**Comment by brian-brazil** [comment]
Many requests will contain secrets, as may some responses, so these cannot be logged.

**Comment by BrentDouglas** [comment]
@stuartnelson3 I'm not sure if this is something that you guys would be interested but I was trying to work out why a bunch of alerts were failing the other day and ended up shipping this binary to the server to work it out. I figure this should be enabled in the config/log levels somehow as this is only really something that will be wanted while debugging but I thought I would open this to see if you would be interested.
I don't really work on go stuff so I'm not going to look into how you would go about enable/disabling this kind of logging unless you indicate that its something you might want.

**Comment by BrentDouglas** [comment]
@brian-brazil Hi Brian, as I mentioned above I don't want to merge this in its current state. I think it would make debugging broken alerts much easier if an option were added to enable logging this info though. It looks like other people have wanted the same debug info in the past (#270).

I agree that this is not something that I would always want in the logs but I think the option of enabling it for debugging would be super useful.

**Comment by brian-brazil** [comment]
> I agree that this is not something that I would always want in the logs but I think the option of enabling it for debugging would be super useful.

Our standard way of enabling debug logs would also violate our security policies, as we promise never to expose explicitly flagged secrets in logs: https://prometheus.io/docs/operating/security/#secrets

**Comment by BrentDouglas** [comment]
Ok. No worries

**Comment by mxinden** [comment]
https://github.com/prometheus/alertmanager/issues/1541 relates to this.

While I think the security promise to never log secrets is very valuable, it makes debugging notifiers very hard. Would enabling more detailed logging on log level *debug* be something we could change the security policy to in the long run?

Something like:

> Fields containing secrets in configuration files (marked explicitly as such in the documentation) will not be exposed in logs **(except debug level)** or via the HTTP API.

 (//CC @stuartnelson3 @brian-brazil)

**Comment by simonpasquier** [comment]
I'd rather see this responsibility delegated to the integration itself. In the case of #1541, the [PagerDuty v2 API](https://v2.developer.pagerduty.com/v2/page/events-api-reference#!/Event/post_create_event_json) states that the response has an optional `message` field defined as "`A description of the problem, or "Event processed" if successful`". I would have no problem with the PagerDuty notifier adding this field (if present) to the error message.

**Comment by brian-brazil** [comment]
> Would enabling more detailed logging on log level debug be something we could change the security policy to in the long run?

Users enable debug logging for all sorts of reasons, and may not expect secrets to be revealed by it if they're e.g. debugging alerts coming into the AM. I'd rather not have a security gotcha like that.

**Comment by vitroth** [comment]
@simonpasquier The problem as I see it is that frequently the response `message` is not informative enough or actually doesn't match the problem.  While thats a usability issue with PagerDuty's API, we need more information exposed to us so we can identify why PD is returning an error on the alert.

**Pull request closed without merging**
