### PR TITLE
Add SkipAuth option for SMTP

### PR DESCRIPTION
**Pull request by povilasv**
So I have a very weird SMTP mail server, which can only used by skipping auth. 

If you guys like the PR I can improve docs if you point me to the right direction :)

### CODE REVIEW

**Comment by aixeshunter** [comment]
@povilasv hi, the `CI` was failed in `TestEmptyFieldsAndRegex `

**Comment by povilasv** [comment]
Thanks @aixeshunter for noting, fixed :)

**Comment by aixeshunter** [comment]
> Thanks @aixeshunter for noting, fixed :)

Looks good :+1:

**Comment by simonpasquier** [comment]
@povilasv thanks for the PR. That's already addressed by https://github.com/prometheus/alertmanager/pull/1739

**Comment by povilasv** [comment]
@simonpasquier cool, that's great. I'll close my pr.

**Pull request closed without merging**
