### PR TITLE
Fix makefile parallelism

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by grobie** [comment]
Makefile.COMMON?

**Comment by juliusv** [comment]
@grobie Makefile.COMMON needs some additions to work with the extra requirements here. So for now, only this fix.

**Comment by juliusv** [comment]
But Makefile.COMMON has the same problem... (will fix either today or tomorrow - probably tomorrow).

**Comment by juliusv** [comment]
Will merge if no further comments for now?

**Pull request merged**
