### PR TITLE
email: generate message ID headers

### PR DESCRIPTION
**Pull request by ddevault**
This GenerateMessageId is taken from go-message:

https://github.com/emersion/go-message/blob/master/mail/mail.go

I am the original author of this file; I agree to distribute it in
alertmanager regardless of the original license.

Signed-off-by: Drew DeVault <sir@cmpwn.com>

### CODE REVIEW

**Comment by ddevault** [comment]
I'm not familiar with dep. How do I update this to account for the new dependency?

**Comment by simonpasquier** [comment]
Thanks for the PR!

For vendoring, you would need to run `make unused` (or `GO111MODULE=on go mod vendor`) and commit any change in the `vendor/` directory.

The Message-ID header is already set before the code you've added so your change would need to go there:

https://github.com/prometheus/alertmanager/blob/b4ac213809a96fe6d834303d61a60bc71a9d356a/notify/email/email.go#L248-L250

And you can notice that the hostname is retrieved only once when the struct is initialized (eg no need to call `os.Hostname()` for every notification).

**Comment by ddevault** [comment]
Hm, I wonder why the existing message ID code wasn't working as expected. I should have caught that. I'll investigate further.

**Comment by simonpasquier** [comment]
this was added quite recently (in the latest release in fact) so maybe you were running an older version of Alertmanager

**Comment by ddevault** [comment]
That'll be it, I'm on 0.19.Cheers!

**Pull request closed without merging**
