### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by oddlittlebird**
Minor edit to clarify  DCO requirement

### CODE REVIEW

**Comment by simonpasquier** [comment]
You can still make changes through the UI but you have to add the `Signed-Off-By: ...` manually in the commit message.
There's also a Firefox [extension](https://github.com/scottrigby/dco-gh-ui) that can do it for you but in general, first-time contributors won't have it installed...

**Comment by oddlittlebird** [comment]
I tried putting "Signed-Off-By: oddlittlebird" in both fields in the commit, neither seems to work.

**Comment by simonpasquier** [comment]
I've done a test (https://github.com/prometheus/alertmanager/pull/2038) and it works for me. The `Signed-off-by` portion needs to include your username **and** email address.

**Comment by oddlittlebird** [comment]
So format is:

Signed-off by: oddlittlebird oddlittlebird@gmail.com

Correct?

For the doc, should we say name or username?

**Comment by oddlittlebird** [comment]
Hallelujah. It worked.

**Review by skorpy2009 — APPROVED** [review]

**Pull request closed without merging**
