### PR TITLE
Sort alerts by their fingerprint

### PR DESCRIPTION
**Pull request by stuartnelson3**
addresses #812 

@fabxc @brancz @mxinden opinion on using `Fingerprint`?

### CODE REVIEW

**Comment by brancz** [comment]
Not sure how to message this or whether that is necessary at all, but we need to make sure that this is just a default sorting order, that happens to be consistent at the moment, and that this behavior may change at any moment. Those things are easy for things like config files, that have documentation, but for front-end it's harder, but we also don't want to confuse people who start using it, however, given the current behavior, this is already much better, so probably nothing to worry about.

**Comment by mxinden** [comment]
@stuartnelson3 @brancz Why not use `StartsAt`? Both `StartsAt` and `Fingerprint` would serve a consistent ordering, but `StartsAt` would additionally give a human useful sorting?

**Comment by brancz** [comment]
I can't find right now in which issue I commented this, but I think sorting by fingerprint is the default that the backend should always apply, and then additional sorting should be configured by the front-end explicitly, but sorting by `StartAt` could be a useful default selection in the front-end. Just my two cents, don't really have a very strong opinion.

**Comment by brancz** [comment]
code lgtm, but there is something wrong with `bindata.go` on Travis CI. Also we'll need to keep in mind what to do if we want to have pagination as we probably don't want to sort all records, but we can think of that when the time comes, just want to make sure this is not set in stone, if we encounter problems with it, I think we can be free to change this behavior.

**Comment by mxinden** [comment]
The failure on Travis was just a flake. I have re-triggered it, all green now.

**Comment by mxinden** [comment]
Thanks @stuartnelson3!

**Pull request merged**
