### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by SuperQ**
* Drop /vendor.
* Update tests to Go 1.15.
* Update djfarrelly/maildev to 1.1.0.
* Update mixin test for Go 1.16.
* Bump Go modules.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
For some reason, the acceptance tests fail with Go 1.16. Only bumping to 1.15 for now.

**Comment by SuperQ** [comment]
Also, there have been some changes to prometheus/common, so I've held that back.

**Comment by roidelapluie** [comment]
You can rebase.

**Comment by SuperQ** [comment]
Ready for review finally.

**Review by roidelapluie — APPROVED** [review]

**Pull request merged**
