### PR TITLE
Add receiver name to the alerts page

### PR DESCRIPTION
**Pull request by roidelapluie**
cc @gotjosh

### CODE REVIEW

**Review by gotjosh — APPROVED** [review]
LGTM!

This is great, thank you so much 🙇

**Comment by gotjosh** [comment]
Screenshot 2023-03-08 at 18 23 21

**Comment by roidelapluie** [comment]
I have improved this a lot. Can you test again?

**Comment by gotjosh** [comment]
Aesthetically looks much better 👌 

Two things:

- The alert list will now look like a staircase because it is dependant on the name of the receiver 😭 I'd rather have it on the other side next to the alert count.
- The whitespace to indicate the indication when you open the group is a bit big

Neither of us are Elm experts so I'm more than happy to proceed with this as is and improve later as this is already a big step up from what we got 👍

**Comment by roidelapluie** [comment]
What do you mean about The alert list will now look like a staircase because it is dependant on the name of the receiver ?

**Comment by roidelapluie** [comment]
Do you mean the labels are unaligned?

**Comment by gotjosh** [comment]
> The alert list will now look like a staircase because it is dependent on the name of the receiver 😭 I'd rather have it on the other side next to the alert count.

Notice how the "team-db-pager" receiver it's just a few extra letters more than the others, in the case where your receiver name letter count is varied, the indentation will look all over the place. Whereas before, every would look uniform as part of the pills. 

Screenshot 2023-03-09 at 14 01 52

**Comment by roidelapluie** [comment]
My recommendation is that we use this implementation for now and consider any future improvements later. Currently, the page isn't completely informative and adding some labels may assist, which would move labels around anyway.

**Comment by gotjosh** [comment]
I 100% agree agree with that sentiment

> Neither of us are Elm experts so I'm more than happy to proceed with this as is and improve later as this is already a big step up from what we got 👍

**Review by gotjosh — APPROVED** [review]
LGTM

**Pull request merged**
