### PR TITLE
test: add reload test

### PR DESCRIPTION
**Pull request by fabxc**
This test reloads the Alertmanager to verify, that it properly keeps
state and sends notifications correctly across reloads.

### CODE REVIEW

**Comment by stuartnelson3** [comment]
Is this to test the code merged in https://github.com/prometheus/alertmanager/pull/703?

**Comment by fabxc** [comment]
No, just adedd it for an unrelated bug report.

**Comment by stuartnelson3** [comment]
Is there a git sha I can check out to verify this test was failing but is now passing?

**Comment by fabxc** [comment]
It's not a regression test. See #627.

**Pull request merged**
