### PR TITLE
Support default SMTP TLS config

### PR DESCRIPTION
**Pull request by sathieu**
Fixes: #3709

```yaml
global:
  smtp_from: 'dont-reply@blabla.com'
  # smtp_smarthost: 'mail.blabla.com:465'
  smtp_smarthost: '10.0.0.1:465'
  smtp_auth_username: 'dont-reply@blabla.com'
  smtp_auth_password: 'randompasss'
  smtp_require_tls: false
  smtp_tls_config:                 # \\\
    insecure_skip_verify: true     #  >>> NEW!
  
receivers:
  - name: myreceiver
    email_configs:
      - to: 'bla@blabla.com'
```

### CODE REVIEW

**Comment by rahilarious** [comment]
Whoa! That was a quick one. Thanks for working on it.

**Review by TheMeier — APPROVED** [review]

**Comment by sathieu** [comment]
@TheMeier You approved the changes. Who can merge?

🙏

**Comment by TheMeier** [comment]
The maintainers https://github.com/prometheus/alertmanager/blob/main/MAINTAINERS.md

**Comment by sathieu** [comment]
@simonpasquierPlease please review this PR adding default `tls_config` for email receivers :pray:.

**Comment by sathieu** [comment]
@simonpasquier Please please review this PR adding default `tls_config` for email receivers :pray:.

**Comment by sathieu** [comment]
@simonpasquier @w0rm @gotjosh Please review this PR :pray:.

**Comment by sathieu** [comment]
@simonpasquier @w0rm @gotjosh friendly reminder to review this PR 🙏 ...

**Review by simonpasquier — APPROVED** [review]
Thanks!

**Comment by sathieu** [comment]
@simonpasquier Is there a new release soon?

**Pull request merged**
