### PR TITLE
HA AM silence adjustments in UI

### PR DESCRIPTION
**Pull request by fabxc**
@beorn7 @brian-brazil 

Please try it out – UI is really not my thing.

### CODE REVIEW

**Comment by beorn7** [comment]
Not a UI person either…

This looks good in general. What worries me a bit is the `new Date` in the functions. This could give us an inconsistent representation of silences with unlucky timing (silences displayed twice or not at all). How about adding a "now" argument to each of those functions that now contain a `new Date` call so that we have a single notion of "now" throughout rendering of one page?

**Comment by fabxc** [comment]
Totally agree on the  `new Date` part. It was a the safe route as I'm not 100% sure what's invoked when with the bi-directional data binding, which could even cause more weirdnesses.

**Comment by fabxc** [comment]
Made some changes @beorn7

**Comment by beorn7** [comment]
OK, thanks. I like it, and it all seemed to work perfectly when I tried it out.

I'm not really qualified about angular and such, but if nobody else wants to comment, then :+1:

**Pull request merged**
