### PR TITLE
Fix comments as per Josh's feedback

### PR DESCRIPTION
**Pull request by grobinson-grafana**
Some feedback from @gotjosh that was missed before https://github.com/prometheus/alertmanager/pull/3278 was closed.

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
oops, my bad!

**Comment by grobinson-grafana** [comment]
Not a problem, thanks for the quick approve! ❤️

**Comment by grobinson-grafana** [comment]
Test failed for nflogs, forced pushed to restart tests.

**Review by gotjosh — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
