### PR TITLE
Update prometheus/common and add support for --log.format

### PR DESCRIPTION
**Pull request by kfdm**
I am not sure if I did this correctly, but I'm willing to accept guidance on how to format things properly. :)

This should handle --log.format for #1657

### CODE REVIEW

**Comment by kfdm** [comment]
Ok, I'll take care of that tomorrow. :)

**Comment by kfdm** [comment]
Assuming that Prometheus is considered an external package from alertmanager's perspective, I believe I have grouped the packages as requested.

**Comment by simonpasquier** [comment]
Agreed, the problem exists in the current code base and isn't specific to your change. This group should be split into 2:

https://github.com/prometheus/alertmanager/blob/f1d33fbcc2bdb6e2661333f954cc540b704633ab/cmd/alertmanager/main.go#L33-L53

**Comment by simonpasquier** [comment]
Ah sorry, I missed the latest update! All good then :+1:

**Pull request merged**
