### PR TITLE
UI cleanup dead code with elm-review

### PR DESCRIPTION
**Pull request by w0rm**
Installed [elm-review](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/) and used it to cleanup dead code.

### CODE REVIEW

**Comment by roidelapluie** [comment]
Is this called during CI too ?

**Comment by w0rm** [comment]
@roidelapluie I've been thinking of adding this, but I am not sure whether we want to be so strict to contributors.

**Comment by roidelapluie** [comment]
> @roidelapluie I've been thinking of adding this, but I am not sure whether we want to be so strict to contributors.

It is your call, is there a way to document this or make this a "non-strict check"?

**Comment by w0rm** [comment]
@roidelapluie good point. I will figure a way to update the docs and include the elm-review tool into the dev docker container.

**Review by roidelapluie — APPROVED** [review]
LGTM

**Comment by w0rm** [comment]
@roidelapluie apologies for the delay. Just clicked through the UI to make sure everything works. Will update the docs in the separate PR.

**Pull request merged**
