### PR TITLE
Make a note about the firewall in HA mode

### PR DESCRIPTION
**Pull request by giganteous**
It took me quite some digging, I hope this helps others (e.g. #1550)

as side note: Without turning on debug logs, it doesn't really show the clustering is not working. Shall I report that as an issue?

### CODE REVIEW

**Comment by stuartnelson3** [comment]
>as side note: Without turning on debug logs, it doesn't really show the clustering is not working. Shall I report that as an issue?

Yeah, report it as an issue and we'll figure out how best to surface this. Maybe drawing attention to it in the UI or something.

**Comment by mxinden** [comment]
According to the docs memberlist falls back to TCP if it can not connect via UDP. Is that not the case?

**Comment by stuartnelson3** [comment]
Hm, I've never tested that behavior (I also wasn't aware of it). The standard behavior is to do small delta changes via UDP and the full-sync via TCP, so maybe we need to reword this, but I still think we should mention that both protocols are expected for normal operation.

**Comment by Hashfyre** [comment]
Somehow the website still doesn't show the update in this PR:
https://prometheus.io/docs/alerting/alertmanager/#high-availability

**Comment by simonpasquier** [comment]
@Hashfyre it is because this PR modified the README file of the repository but the documentation you pointed is at https://github.com/prometheus/docs/blob/master/content/docs/alerting/alertmanager.md. Do you want to open a PR there?

**Pull request merged**
