### PR TITLE
feat(discord): add global and secret file for discord notifier

### PR DESCRIPTION
**Pull request by budimanjojo**
This enable the ability for `discord` notifier to use a file instead of plain secret.
This also adds the `global.discord_webhook_url` and `global.discord_webhook_url_file`

### CODE REVIEW

**Review by simonpasquier — COMMENTED** [review]
We need to check that both `DiscordWebhookURL` and `DiscordWebhookURLFile` aren't defined at the same time in the global section.

**Comment by simonpasquier** [comment]
I'm not sure about the CircleCI error but could you try rebasing your PR on top of main? Adding some unit tests would be appreciated too (you can look at notify/opsgenie/opsgenie_test.go for inspiration).

**Comment by budimanjojo** [comment]
sorry I messed up the rebase rofl. I'm trying

**Comment by budimanjojo** [comment]
is this good now?

**Comment by LucaDev** [comment]
This feature was introduced by #3555

**Comment by budimanjojo** [comment]
Thanks for the information @LucaDev! Closing this one.

**Pull request closed without merging**
