### PR TITLE
Templating the Slack API URL

### PR DESCRIPTION
**Pull request by hairyhenderson**
I'd like to be able to template parts of the Slack API URL. This PR allows that.

/cc @stuartnelson3

Signed-off-by: Dave Henderson <dhenderson@gmail.com>

### CODE REVIEW

**Comment by brian-brazil** [comment]
Can you explain why you want to template this?

**Comment by hairyhenderson** [comment]
@brian-brazil The URL is effectively a secret, and I want to be able to store it separate from the AM config. This can be done for other secrets (such as `pagerduty`'s `routing_key`), since they're templated.

**Comment by brian-brazil** [comment]
Templating of things like this is for routing, not for secrets and it'd generally a bad idea to use the templating like this as anyone who can change the config will be able to exfiltrate them.
See https://prometheus.io/docs/operating/security/#alertmanager

`routing_key` is templatable in spite of being a secret, not because it is one.

**Comment by hairyhenderson** [comment]
Ok, understood. I'll have to approach this differently, then 👍

**Pull request closed without merging**
