### PR TITLE
Add a `-` section to Config for storing variables

### PR DESCRIPTION
**Pull request by sylr**
E.G.:

```yaml
-:
  slack_format: &slack_format
    color: |-
      {{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "warning" }}warning{{ else }}danger{{ end }}{{ else }}good{{ end }}
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}
    text: |-
      {{- range .Alerts }}*{{ .Annotations.description }}*
      {{ .Annotations.summary }}
      {{ if eq .Status "firing" -}}
        {{- if .Annotations.alert_title_labels -}}
          {{- $allowed_labels := split "," .Annotations.alert_title_labels -}}
          {{- with .Labels.Select $allowed_labels -}}
      ```{{ range .SortedPairs -}}
      {{ .Name }} = {{ .Value }}
      {{ end -}}```
          {{- end -}}
        {{- else -}}
      ```{{ range .Labels.SortedPairs -}}
      {{ .Name }} = {{ .Value }}
      {{ end -}}```
        {{- end -}}
      {{- end }}
      {{ end }}

receivers:
- name: a
  slack_configs:
  - send_resolved: true
    username: "..."
    api_url: "https://hooks.slack.com/services/..."
    <<: *slack_format
- name: b
  slack_configs:
  - send_resolved: true
    username: "..."
    api_url: "https://hooks.slack.com/services/..."
    <<: *slack_format
```

### CODE REVIEW

**Comment by brian-brazil** [comment]
I concur with @roidelapluie

**Comment by sylr** [comment]
@roidelapluie @simonpasquier I made some changes, what about now ?

**Comment by brian-brazil** [comment]
I still think this is something we should not have, and am generally quite wary of using YAML references as it's a poor man's configuration management.

**Comment by sylr** [comment]
@brian-brazil If you don't want it then don't, that's not a reason to forbid others to do it.

**Comment by brian-brazil** [comment]
It is our general policy that we don't add features whose primary purpose is to workaround a lack of configuration management.

**Comment by sylr** [comment]
I'm just trying to factorize a block of configuration that is going to be repeated a bunch of times, configuration management isn't going to help me with that.

**Comment by brian-brazil** [comment]
That's exactly the sort of thing configuration management should be helping you with, via templating and/or inheritance.

**Comment by roidelapluie** [comment]
```
receivers:
- name: a
  slack_configs:
  - send_resolved: true
    username: "..."
    api_url: "https://hooks.slack.com/services/..."
    slack_format: &slack_format
      color: |-
      {{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "warning" }}warning{{ else }}danger{{ end }}{{ else }}good{{ end }}
      title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}
      text: |-
      {{- range .Alerts }}*{{ .Annotations.description }}*
      {{ .Annotations.summary }}
      {{ if eq .Status "firing" -}}
        {{- if .Annotations.alert_title_labels -}}
          {{- $allowed_labels := split "," .Annotations.alert_title_labels -}}
          {{- with .Labels.Select $allowed_labels -}}
      ```{{ range .SortedPairs -}}
      {{ .Name }} = {{ .Value }}
      {{ end -}}```
          {{- end -}}
        {{- else -}}
      ```{{ range .Labels.SortedPairs -}}
      {{ .Name }} = {{ .Value }}
      {{ end -}}```
        {{- end -}}
      {{- end }}
      {{ end }}
- name: b
  slack_configs:
  - send_resolved: true
    username: "..."
    api_url: "https://hooks.slack.com/services/..."
    slack_format: *slack_format
```


how is that working for you?

**Comment by roidelapluie** [comment]
The solution I propose last seems to be working and does not need any change at the AM level.

**Pull request closed without merging**
