### PR TITLE
fix lint error

### PR DESCRIPTION
**Pull request by clyang82**
There are new rules defined in https://github.com/grafana/dashboard-linter. some of rules are strict. so add them into exclusions.

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Comment by clyang82** [comment]
wait for this PR - https://github.com/grafana/dashboard-linter/pull/10 to fix the remaining lint error

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
thanks!

**Pull request merged**
