### PR TITLE
mark webhook URL as a secret

### PR DESCRIPTION
**Pull request by sr**
As discussed in https://github.com/prometheus/alertmanager/pull/3223

/cc @gotjosh @simonpasquier

### CODE REVIEW

**Review by gotjosh — APPROVED** [review]
LGTM

**Comment by gotjosh** [comment]
Any thoughts @simonpasquier?

**Comment by simonpasquier** [comment]
> Should I update the changelog or will you take care of it?

No, whoever is going to shepherd/review the next release should be vigilant. And yes #3223 is useful.

**Comment by gotjosh** [comment]
> No, whoever is going to shepherd/review the next release should be vigilant. 

I'll keep it in mind.

**Pull request merged**
