### PR TITLE
Add JSON marshaling to config.Matchers

### PR DESCRIPTION
**Pull request by beorn7**
I have found out that we still need this for the v1 API (and possibly
elsewhere).

@aSquare14 could you have a look?

### CODE REVIEW

**Review by aSquare14 — APPROVED** [review]

**Comment by roidelapluie** [comment]
Note that v1 can not be deprecated as it is used by prometheus server by default

**Comment by aSquare14** [comment]
LGTM. Thank you

**Comment by beorn7** [comment]
Wasn't the plan to move to using v2 by default in prometheus/prometheus?

**Comment by roidelapluie** [comment]
> Wasn't the plan to move to using v2 by default in prometheus/prometheus?

Created an issue in prometheus to discuss this.

**Pull request merged**
