### PR TITLE
Add image build for ppc64le architecture

### PR DESCRIPTION
**Pull request by carlosedp**
Add image build for ppc64le architecture

Signed-off-by: Carlos de Paula <me@carlosedp.com>

### CODE REVIEW

**Comment by simonpasquier** [comment]
Thanks!

**Comment by carlosedp** [comment]
Any plans on when a new version will be cut so the images get generated?

**Comment by simonpasquier** [comment]
No plan yet though v0.20 is old enough that a new release would be welcomed. If you really need to, you can use the `master` tag.

**Comment by carlosedp** [comment]
Sure, thanks. Can you take a look at the Prometheus PR too?
https://github.com/prometheus/prometheus/pull/7067

**Pull request merged**
