### PR TITLE
Adding `/api/v2` prefix to all endpoints in OpenAPI specification

### PR DESCRIPTION
**Pull request by dannykopping**
All API endpoints are prefixed with `/api/v2`

### CODE REVIEW

**Comment by dannykopping** [comment]
Appears that some flaky test is obstructing the CI from passing

**Comment by roidelapluie** [comment]
openapi has dedicated prefix: setting for this.

**Comment by dannykopping** [comment]
> openapi has dedicated prefix: setting for this.

I looked for it, but couldn't find it; I'm not very familiar with OpenAPI.
Could you direct me to it pls?

**Comment by roidelapluie** [comment]
basePath

**Comment by roidelapluie** [comment]
Look for basePath here: https://swagger.io/specification/v2/

**Comment by dannykopping** [comment]
Ah, thanks @roidelapluie. I'm curious - are many people using the client library?
If so, I'd imagine that someone must've come across this issue?

Some context:
I'm not using it, but [this page](https://prometheus.io/docs/alerting/latest/clients/) directed me to the openapi spec. I wanted to send a test alert to AM via the API, and struggled to find the correct API path to use.

**Comment by roidelapluie** [comment]
tests are all broken now. I wonder if that is a valid change since the basePath must be at the root but you can change it with flags ..

**Comment by dannykopping** [comment]
Indeed. I think I'll close this, and we can revive if necessary.

**Comment by roidelapluie** [comment]
I don't think we should close this, we should fix the tests and see what the result is.

We better fix this now than after 1.0 is released.

**Comment by dannykopping** [comment]
Alright. What do you suggest we do regarding the tests?
I'm new to the codebase.

**Comment by JohnnyQQQQ** [comment]
When adding a `basePath` the generated server automatically has this path. But we add it already in `api.go` in line 190.

https://github.com/prometheus/alertmanager/blob/fad796931b792fc30f35bb18a580ae7323ef0241/api/api.go#L189-L192

So we end up with a path like `/api/v2/api/v2`, you can check this locally starting an instance an opening the `api/v2/api/v2/status` endpoint.

It seems sensible to have the `basePath` set correctly to generate the clients and server with the correct path embedded. I'm not sure what the best solution could be here. 

cc @roidelapluie

**Comment by JohnnyQQQQ** [comment]
I did dig a bit deeper. The problem is in line 191. We don't need `StripePrefix` anymore. 

Let me explain in detail. 

We serve the Handler under the `/api/v2/` route. The **Handler** is excepting Requests with a `/api/v2/` prefix. By removing the prefix, you require adding it again to make the request work. That's why `/api/v2/api/v2/status` works. As we strip `/api/v2` one time with `StripePrefix`, making it correct.

By simply removing the `/api/v2/` part from `StripPrefix` everything should work. I tested it locally and opened a PR to your branch (https://github.com/dannykopping/alertmanager/pull/1).

**Comment by dannykopping** [comment]
> I did dig a bit deeper. The problem is in line 191. We don't need `StripePrefix` anymore.
> 
> Let me explain in detail.
> 
> We serve the Handler under the `/api/v2/` route. The **Handler** is expecting Requests with a `/api/v2/` prefix. By removing the prefix, you require adding it again to make the request work. That's why `/api/v2/api/v2/status` works. As we strip `/api/v2` one time with `StripePrefix`, making it correct.
> 
> By simply removing the `/api/v2/` part from `StripPrefix` everything should work. I tested it locally and opened a PR to your branch ([dannykopping#1](https://github.com/dannykopping/alertmanager/pull/1)).

Thanks for that @JohnnyQQQQ!

**Comment by dannykopping** [comment]
Hhmm, looks like the DCO build stage is failing now from your last commit

**Comment by JohnnyQQQQ** [comment]
@dannykopping  Sorry yeah, you need to do the steps mentioned here https://github.com/prometheus/alertmanager/pull/2696/checks?check_run_id=4187219569

**Comment by dannykopping** [comment]
> @dannykopping Sorry yeah, you need to do the steps mentioned here https://github.com/prometheus/alertmanager/pull/2696/checks?check_run_id=4187219569

You're right; i thought you'd have to sign your commit, but turns out i can sign your tweet and keep your authorship :+1:

**Comment by roidelapluie** [comment]
Thanks!

**Comment by amitvermaa3101** [comment]
Please suggest if alertmanager UI is available to manage silence or other things

**Pull request merged**
