### PR TITLE
feat: add time helpers

### LINKED ISSUE #3717: Missing a way to use time.Since and pretty format duration in templates
I want to be able to use a custom template to display the time the alert started to fire and how much time is it firing for, something like:

`⌛ Firing since: 2024-02-12 18:15:38.457 +0000 UTC (for 3 hours 42 minutes 21 seconds)`.

We already have .StartsAt field for alert, but there's no template helper to 1) use `time.Since()`, and 2) pretty-format duration, so it would be lovely to have it here as well.

### PR DESCRIPTION
**Pull request by freak12techno**
Closes #3717.

Bumps prometheus/common to latest, imports HumanizeDuration from it and exposes it and time.Since as template methods.
Also added some tests for templating it (which is mostly copypaste from Prometheus repo).

Here's how the alert would look like:

Template part (the one specifying how to render):
```
{{ define "alerts_list" }}
{{ range . }}{{ if index .Labels "host" -}}
🖥️ Host: {{ index .Labels "host" }} ({{ index .Labels "instance" }})
{{- else -}}
🖥️ Host: {{ index .Labels "instance" }}
{{- end }}
{{ if eq (index .Labels "severity") "critical" -}}
🔴 Severity: critical
{{- else -}}
🟠 Severity: warning
{{- end }}
📖 Alert: {{ index .Labels "alertname" }}
ℹ️ Details: {{ index .Annotations "summary" }}
⌛ Firing since: {{ .StartsAt }} (for {{ .StartsAt | since | humanizeDuration }})
📝 Description: {{ index .Annotations "description" }}
```

Alert generation:
```
./amtool alert add --alertmanager.url http://localhost:9093 alertname=aaa host=test instance=test3
```

Alert received in Telegram (the "Starts at" thing was displayed this way before and I haven't touched it; main thing is the "for 10s" block):
изображение

### CODE REVIEW

**Comment by freak12techno** [comment]
@gotjosh mind looking at it?

**Comment by gotjosh** [comment]
Can you please fix the go.mod?

**Comment by freak12techno** [comment]
@gotjosh done

**Comment by freak12techno** [comment]
(I checked the CI failures, all of them shouldn't be caused by my changes, but can someone please confirm this?)

**Comment by gotjosh** [comment]
Can you rebase?

**Comment by freak12techno** [comment]
@gotjosh it says it's up to date

**Comment by freak12techno** [comment]
@gotjosh sounds like a nice idea, but it'll require another bump of prometheus/common. I suggest moving it to another PR, which I will also do, is it ok?

**Comment by gotjosh** [comment]
Correct, I was not suggesting as part of this PR. I'll merge this right now - thanks very much for your contributions, highly appreciated.

**Pull request merged**
