### PR TITLE
Add discord message fields

### PR DESCRIPTION
**Pull request by yaskinny**
This PR adds some fields to Discord message like Content which is already mentioned in issue #3667.

Being able to set _Content_ is really important to have since at this moment, there is no way to tag users in alerts. Default Discord 
template embeds alerts and in Discord, ATM, tagging someone in embedded fields, does not tag them. It will just include user/role name without sending notification like when you get tagged in normal message.

Discord code [already](https://github.com/prometheus/alertmanager/blob/main/notify/discord/discord.go#L77) had `content` field but it's not used in the code nor config.

I added other fields like avatar url and username.

Below content are example configs and result:
Alertmanager receiver config:
```yaml

receivers:
  - name: 'discord'
    discord_configs:
    - webhook_url: 'https://discord.com/api/webhooks/1153054938155450368/kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkEwc3KouoUWE4'
      content: '{{ template "my.content" . }}'
      avatar_url: 'https://www.tbstat.com/wp/uploads/2023/05/Fvz9hOIXwAEaIR8-669x675.jpeg'
      username: GOFW
```

Template:
```
{{- define "my.content" }}
tags: {{- range .Alerts }}
{{- if .Annotations.tags }}
{{- reReplaceAll "," " " .Annotations.tags }}
{{- end }}
{{- end }}
{{- end }}
```

Prometheus alert:
```yaml
---
groups:
- name: watchdogs
  rules:
  - alert: WatchDog-1
    expr: vector(1)
    labels:
      severity: info
    annotations:
      summary: "WatchDog1"
      description: "FAKE"
      tags: '<@5132333333333336177>,<@5132333333333336177>'
        
  - alert: WatchDog-2
    expr: vector(2)
    labels:
      severity: critical
    annotations:
      summary: "WatchDog2"
      description: "FAKE"
      tags: '<@5132333333333336177>,<@5132333333333336177>'

```

Screenshot from 2024-04-26 20-04-24

### CODE REVIEW

**Comment by grobinson-grafana** [comment]
@yaskinny can you signoff your commits? That will fix the DCO check 🙂

**Comment by yaskinny** [comment]
also it might be beneficial to edit the default discord template in a way that older config version(without username/content) works without any issue after updating to newer alertmanager version.

like making username/content optional in the template. since at this point, users need to rewrite their own template if they want to use username/content fields. with updating default template, it will has better UX since by default it will be included in the alerts.

@grobinson-grafana let me know if you want me to work on that or not.

**Comment by grobinson-grafana** [comment]
> also it might be beneficial to edit the default discord template in a way that older config version(without username/content) works without any issue after updating to newer alertmanager version.
> 
> like making username/content optional in the template. since at this point, users need to rewrite their own template if they want to use username/content fields. with updating default template, it will has better UX since by default it will be included in the alerts.

I'm not sure I understand. What are you suggesting?

**Comment by yaskinny** [comment]
@grobinson-grafana 

I mean the default Discord template does not include the _content_ field.  
[https://github.com/prometheus/alertmanager/blob/e5821b78917591a5603e3e1788b6a94d5b2972e0/template/default.tmpl#L126-L136](https://github.com/prometheus/alertmanager/blob/e5821b78917591a5603e3e1788b6a94d5b2972e0/template/default.tmpl#L126-L136)

It would be better if the default template used the _content_ field to allow anyone who uses the _content_ option to utilize it without having to write their own template from scratch. However, since older versions of Alertmanager do not include the _content_ field, we need to make it optional (use a condition in the template to check if _content_ is set before using it). By making it optional, users won't face errors after updating to the new Alertmanager version.

**Comment by grobinson-grafana** [comment]
> @grobinson-grafana
> 
> I mean the default Discord template does not include the _content_ field.
> 
> https://github.com/prometheus/alertmanager/blob/e5821b78917591a5603e3e1788b6a94d5b2972e0/template/default.tmpl#L126-L136
> 
> It would be better if the default template used the _content_ field to allow anyone who uses the _content_ option to utilize it without having to write their own template from scratch. However, since older versions of Alertmanager do not include the _content_ field, we need to make it optional (use a condition in the template to check if _content_ is set before using it). By making it optional, users won't face errors after updating to the new Alertmanager version.

Is the suggestion to also replace the embeds with content? If not, what would the default template for `content` be and what would happen to the embeds?

**Comment by grobinson-grafana** [comment]
You might also want to check out https://github.com/prometheus/alertmanager/pull/3761 which extends the use of embeds.

**Comment by mogoll92** [comment]
> You might also want to check out #3761 which extends the use of embeds.

I think he meant don't touch embedded at all just to make content field configurable, atm we have it just in webhook struct but does use nowhere. 
```
type webhook struct {
	Content string         `json:"content"`
	Embeds  []webhookEmbed `json:"embeds"`
}
```
It would be really useful as for some custom solutions you would like to mention users over user_id or role_id and make sure they got notification. In current implementation of discord embedded everything that is tagged inside embedded won't trigger discord notification.

**Comment by gotjosh** [comment]
Duplicate of #4007 and #4081

**Pull request closed without merging**
