### PR TITLE
The default group_by is meant to be no labels.

### PR DESCRIPTION
**Pull request by brian-brazil**
This is what the intended default is, and what
the documentation says.

@stuartnelson3

### CODE REVIEW

**Comment by simonpasquier** [comment]
Closes https://github.com/prometheus/alertmanager/issues/1288

**Comment by stuartnelson3** [comment]
@w0rm are there other places in the code that make special assumptions about a default grouping of `alertname` we need to do something about?

**Comment by w0rm** [comment]
Why do we change the default UI behavior? As far as I remember it was a conscious decision to group alerts by alertname by default to improve usability.

**Comment by brian-brazil** [comment]
I don't see that we have to have the UI in sync with this default.

**Comment by stuartnelson3** [comment]
Ah my mistake, sorry about that

**Pull request merged**
