### PR TITLE
test: Add elm-format job to travis ci configuration

### PR DESCRIPTION
**Pull request by mxinden**
This runs elm-format inside a docker container serving the Elm
environment. Afterwards we check with git if a file changed and fail
accordingly.

### CODE REVIEW

**Comment by mxinden** [comment]
Ready to merge if you don't have objections.

**Comment by w0rm** [comment]
Maybe we should try to compile the project as well.

**Comment by w0rm** [comment]
I commented that we should run `elm make` and see if that passes, but actually the `make` command was already there. I'm not sure if it calls `elm make` though.

**Comment by mxinden** [comment]
@stuartnelson3 added `--validate` flag

@w0rm added `elm-make` job

@stuartnelson3 @w0rm Please rereview. 

Just as a heads up, make sure you update your local `elm-format` version to the newest `0.6.0-alpha` version. Otherwise the CI will fail on your changes.

**Pull request merged**
