### PR TITLE
Add support for security-related HTTP headers

### PR DESCRIPTION
**Pull request by mousavian**
Similar to https://github.com/prometheus/prometheus/pull/9546/

### CODE REVIEW

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
thanks!

**Comment by roidelapluie** [comment]
Close/reopen to trigger CI

**Comment by mousavian** [comment]
Thanks @roidelapluie ,
CI failed on the `go.sum` file tidiness so I committed the updated go.sum file.

**Comment by roidelapluie** [comment]
Close/reopen to trigger CI

again

**Pull request merged**
