### PR TITLE
Allow retry for 429 on webhook receiver

### PR DESCRIPTION
**Pull request by justinwatkinson**
To address #2121 - proposing patch which adds 429 response to the retry codes for webhooks only.

### CODE REVIEW

**Comment by roidelapluie** [comment]
This behavior should be optional and opt-in.

**Comment by brian-brazil** [comment]
This shouldn't be configurable at all, we should have one consistent protocol for webhook. If you want the Alertmanager to retry, a 5xx will do it.

**Comment by justinwatkinson** [comment]
Indeed, 5xx is the state of the world today for some of the things I work on.  It became a discussion on the semantics of a 429 in other contexts including outside of Prometheus.

When I first encountered this, it took a while to dig through the Google group to get to the 5xx answer.  Perhaps a simple doc improvement to clarify this protocol improvement is in order instead?

**Comment by brian-brazil** [comment]
Do we really need to document the basic meaning of HTTP status codes?

**Comment by justinwatkinson** [comment]
What is the desired behavior if Retry-After is included in the 429 response?  I believe as of today its ignored since it is not mandatory, and perhaps that's the most correct way for Alertmanager as the client of the webhook to react.

**Comment by roidelapluie** [comment]
That code does not take care about the Retry-After anyway, so in a way @brian-brazil is right. On the other way, if you want to send your alerts to systems that are not alertmanager specific they could reply with a 429. In that case, should it be the responsibility of the admin to ensure no 429 can come from those?

**Comment by roidelapluie** [comment]
I think that in this case it might be worth it to make it as an option - it will probably not cost much to maintain and might help some users. Now the option could be retry_429 or retriable_codes (default: [5xx]).

**Comment by justinwatkinson** [comment]
Right... I borrowed most of it from the Slack receiver before it was reverted, which also didn't handle Retry-After IIRC.  Feels like it's a good time to kill this PR and continue discussion in the issue anyways.

**Comment by roidelapluie** [comment]
Yes that is why it got reverted ... because it did not respect the retry after :)

**Comment by brian-brazil** [comment]
Keep in mind that webhook receivers are intended to be designed specifically to work with what the Alertmanager sends them, so by that logic the Alertmanager shouldn't need any configuration to decide how to deal with the responses either.

**Comment by simonpasquier** [comment]
I'm also in favor of keeping the webhook notifier simple and stick with retrying only on 5xx.
Alertmanager could handle in a better way notification systems such as Slack that indicate when it's safe to retry.

**Pull request closed without merging**
