### PR TITLE
Update alertmanager.md

### PR DESCRIPTION
**Pull request by stuartcongdon**
Adding link to xMatters direct integration with Alertmanager

### CODE REVIEW

**Review by stuartcongdon — COMMENTED** [review]
Add Signed-off-by

**Comment by gotjosh** [comment]
Is there any precedent to this @roidelapluie or @simonpasquier? While sensible to include a link to xMatters and explicitly name them not sure if the README.

As an example, I don't think Prometheus excitedly names anyone but Soundcloud because that's where it originated from.

**Comment by roidelapluie** [comment]
Links to AM integrations are in the docs repository.

**Comment by roidelapluie** [comment]
https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver

**Comment by gotjosh** [comment]
Seems like xMatters is already listed as part of the integrations 😄

**Comment by simonpasquier** [comment]
Closing this PR since xMatters is already listed in the integrations page.

**Pull request closed without merging**
