### PR TITLE
Fix build problems

### PR DESCRIPTION
**Pull request by beorn7**
This will fix the errcheck problems, and it might have an impact on the `go generate` part.

It indeed looks like Circle somehow keeps `GOPATH` in the environment for external commands (via `go generate` or the `errcheck` command), while Travis somehow removes it or builds outside of it or whatever. More investigation needed, but this removes a few parts of the equation at least.

### CODE REVIEW

**Comment by simonpasquier** [comment]
Same conclusion for me: one way or another, Travis CI changed something to their setup and it acts as if the project was outside of `GOPATH`. I noticed that it automatically exports `GO111MODULE=auto` too recently. I wish there was a changelog somewhere...

**Comment by beorn7** [comment]
That's a lead... Still I don't quite get why the `go generate` part is affected in that way. If they still build within `GOPATH`, the `GO111MODULE=auto` should re-create the original go behavior. But somehow, it wants modules, but that doesn't seem to work in the sub dir... or something... Anyway, let's get this merged (on green) so that we have one less thing to distract us from the `go generate` problem.

**Comment by beorn7** [comment]
@simonpasquier fine to merge this?

**Comment by beorn7** [comment]
Since you closed #1748 in lieu if this, I guess yes. Just want to get master green again. Merging now...

**Comment by simonpasquier** [comment]
Thanks for this @beorn7! I'll dig further to understand what has changed and broke...

**Pull request merged**
