### PR TITLE
notify: remove wechat unit test

### LINKED ISSUE #1348: Investigate flaky WeChat test
```
--- FAIL: TestWechat (127.93s)
	Error Trace:	impl_test.go:312
	Error:		Should be false
```

Figure out why this test is intermittently failing on CI.

### PR DESCRIPTION
**Pull request by simonpasquier**
Fixes #1348.

### CODE REVIEW

**Comment by mxinden** [comment]
:+1: Sad to not have any test coverage for the WeChat provider, but better than doing a call to a live system in a unit test.

**Comment by stuartnelson3** [comment]
True. But, part of the deal for adding wechat was that someone using it would maintain it. If it gets in the way of the rest of our test suite, the onus is on them.

**Comment by mxinden** [comment]
Aggreed, thanks for investigating.

**Pull request merged**
