### PR TITLE
Cleanup NOTICE file

### PR DESCRIPTION
**Pull request by SuperQ**
Remove unused bootstrap-datepicker.js entry.

### CODE REVIEW

**Comment by SuperQ** [comment]
Supersedes https://github.com/prometheus/alertmanager/pull/3063

**Review by gotjosh — APPROVED** [review]
LGTM

**Comment by SuperQ** [comment]
I'm not sure what's up with the tests.

**Comment by simonpasquier** [comment]
Trying to fix the template generation in https://github.com/prometheus/alertmanager/pull/3954.

**Pull request merged**
