### PR TITLE
[WIP] Resolve peer names directly

### LINKED ISSUE #929: `-mesh.peer` only uses one record returned by DNS
When using the `-mesh.peer` flag with a DNS name value, only one of the records would be used. It'd be nice to add *all* records. For example, if all alertmanagers were listed in Consul's service catalog, a single DNS name could be used. 

This appears to be a limitation of the weaveworks/mesh library:
https://github.com/prometheus/alertmanager/blob/master/vendor/github.com/weaveworks/mesh/connection_maker.go#L96
which uses `net.ResolveTCPAddr`.

See for discussion: 
https://groups.google.com/forum/#!topic/prometheus-developers/176Pl1uK0aE

### PR DESCRIPTION
**Pull request by simonpasquier**
With this change, AlertManager resolves the peers instead of relying on the mesh library. If a peer's resolution fails be resolved, AlertManager retries it for a minute at most.

This fixes a couple of issues/gaps:

* Avoid dropping peers if they aren't resolved immediately at startup.
* Support for A records returning multiple addresses.

Fixes #929 and #645 (partially for now since it doesn't work with SRV records). Before doing further changes, I wanted to get a feeling whether this is a) useful and b) in the right direction.

cc @stuartnelson3 @iksaif @discordianfish

### CODE REVIEW

**Comment by stuartnelson3** [comment]
From re-reading the discussion, it seems like we settled on a minimal implementation that supports this and srv lookups. (cf. https://github.com/oklog/oklog/blob/master/cmd/oklog/forward.go#L145-L187). I'm personally in favor of scripting around it with e.g. config management, but see where this would make peoples' lives easier with little maintenance penalty.

I'm not sure we need to add all the parallelization code, but that can be discussed later if others still think minimal sd is something to add here.

@brancz @brian-brazil

**Comment by iksaif** [comment]
SRV looking would be great, it would work out the box with things such as Consul. I think if we add more code related to the mesh here it might be a good idea to move all of it in a new file, and maybe wrap it a little bit (will help when somebody starts changing the mesh implementation with something else).

**Comment by simonpasquier** [comment]
@iksaif I've seen your other PR and agree that eventually it should be splitted into a separate file.

**Comment by brian-brazil** [comment]
I'm strongly against SRV lookups, we already have a full service discovery system and I don't believe we should start developing a second parallel system.

**Comment by mjudeikis** [comment]
DNS resolution would solve issues when running it in k8s statefulsets where IP address changes constantly behind DNS
 (https://github.com/prometheus/alertmanager/issues/1206) . 
+1

**Comment by iksaif** [comment]
:+1: , having to script stuff to be able to discover the port isn't super friendly (just getting the IP is easy)

**Comment by simonpasquier** [comment]
Putting this PR on hold as https://github.com/prometheus/alertmanager/pull/1232 revamps the whole mesh thing.

**Comment by discordianfish** [comment]
> From re-reading the discussion, it seems like we settled on a minimal implementation that supports this and srv lookups. (cf. https://github.com/oklog/oklog/blob/master/cmd/oklog/forward.go#L145-L187).

Yes, that's what I strongly want too. And only for initial peer discovery, e.g when creating the mesh the first time or when a new member joins. In it's current form the AM is really hard to setup in dynamic environments.

**Comment by simonpasquier** [comment]
Superseded by the refactoring of the clustering part.

**Pull request closed without merging**
