### PR TITLE
Handle UI timestamp drift

### PR DESCRIPTION
**Pull request by fabxc**
@beorn7

### CODE REVIEW

**Comment by beorn7** [comment]
:+1: 

Looks like the tests are broken in fabx-soha, too. Or they are at least flaky. Would be good to get those fixed so that we don't have to check if the failing tests are the known ones each time.

**Comment by fabxc** [comment]
The functional tests are flaking on CI since they exist.

**Comment by beorn7** [comment]
They are also flaky on my laptop.

**Comment by fabxc** [comment]
Never had that happen macbook pro. Timing is quite genrous - they are all
in parallel though.

I've plans on this but that's better for a later point in time.

**Pull request merged**
