### PR TITLE
Add wechat app group message

### PR DESCRIPTION
**Pull request by hai046**
- Added support for WeChat groups to facilitate communication and sharing of alarm information
添加支持微信群组，便于交流分享报警信息

- add wechat group chat type groupText and groupMarkdown

- add test config and script  and screenshot

  the config at examples/ha/wechat_alertmanager.yml  
  send a alert msg with script: examples/ha/wechat_group_alerts.sh
  the template at : examples/ha/wechat_group*.tmpl

the result group msg:
image

### CODE REVIEW

**Comment by hai046** [comment]
My test alertmanager.yml

```
global:
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: '#wechat_api_secret'
  wechat_api_corp_id: '#wechat corp id '
  resolve_timeout: 1m

route:
  group_by: ['application']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'groupWechat'

templates:
  - /etc/alertmanager/config/*.tmpl
receivers:
  - name: 'groupWechat'
    wechat_configs:
      - send_resolved: true
        to_tag: '服务报警'
        message_type:  'groupMarkdown'
        message: '{{ template "wechat.default.groupMessage" . }}'
        agent_id: '#wechat agent id'
        group_title: '{{ template "wechat.default.groupTitle" . }}'    #create group chatId
        group_users:
          - haizhu
          - FengYu
  - name: 'wechat'
    wechat_configs:
      - send_resolved: true
        to_user: "xxx"
        to_tag: '服务报警'
        message_type:  'groupMarkdown'
        message: '{{ template "wechat.default.message" . }}'
        agent_id: '#wechat agent id'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

```

the script post alerts 
```
#!/usr/bin/env bash
alerts1='[
    {
        "labels": {
            "application": "app1",
            "instance": "instance1",
            "groupTitle": "微服务测试"
        },
        "startsAt": "2021-01-20T14:31:39.000Z",
        "endsAt": "2021-06-28T04:09:43.534Z",
        "annotations": {
            "summary": "summary info",
            "message": "message content"
        },
        "generatorURL": "http://GecyXAtxISsqBCNScCD.xldw-xtmZQKncZJequKpc,2CQ1J7lE-SKEx2i1dYxWDbo071rZFoiN7OQEbKltIARN+"
    },
    {
        "labels": {
            "application": "app1",
            "instance": "instance1",
            "groupTitle": "微服务测试"
        },
        "startsAt": "2021-01-20T14:31:39.000Z",
        "endsAt": "2021-06-28T04:09:43.534Z",
        "annotations": {
            "summary": "summary info2",
            "message": "message content2"
        },
        "generatorURL": "http://GecyXAtxISsqBCNScCD.xldw-xtmZQKncZJequKpc,2CQ1J7lE-SKEx2i1dYxWDbo071rZFoiN7OQEbKltIARN+"
    }
]'
curl -XPOST -d"$alerts1" -H "Content-Type:application/json" http://localhost:9093/api/v2/alerts


```

**Comment by roidelapluie** [comment]
Thanks for your PR. For legal reasons, we require that all commits are signed with a [DCO](https://developercertificate.org/) before we can merge them. See [this blog post](https://www.cncf.io/blog/2016/11/08/cloud-native-software-can-trust/) for considerations around this.

This means that the last line of your commit message should read like:

`Signed-Off-By: Your Name <your@email.address>`

If you are using GitHub through the web interface, it's quickest to close this PR and open a new one with the appropriate line.

If you are using Git on the command line, it is probably quickest to amend and force push. You can do that with
````
git commit --amend --signoff
git push -f $remote $remote_branch_for_pr
````

As always, be careful when force-pushing.

**Comment by roidelapluie** [comment]
I will do a further review later.

**Comment by hai046** [comment]
OK，the auth and email mix ,I  open a new one

**Pull request closed without merging**
