### PR TITLE
feat(env): add auto go maxprocs

### PR DESCRIPTION
**Pull request by dongjiang1989**
this PR is about adding a new dependency on go.uber.go/automaxprocs.

auto set GOMAXPROC for Alertmanager Container by prometheus-operator.

ref: https://github.com/prometheus/prometheus/pull/10498

### CODE REVIEW

**Comment by grobinson-grafana** [comment]
I think this is a duplicate of https://github.com/prometheus/alertmanager/pull/3736.

**Review by simonpasquier — COMMENTED** [review]
Could you add it behind a feature flag with a log like Prometheus?

https://github.com/prometheus/prometheus/blob/d78253319daa62c8f28ed47e40bafcad2dd8b586/cmd/prometheus/main.go#L735-L742

**Comment by dongjiang1989** [comment]
> Could you add it behind a feature flag with a log like Prometheus?
> 
> 
> 
> https://github.com/prometheus/prometheus/blob/d78253319daa62c8f28ed47e40bafcad2dd8b586/cmd/prometheus/main.go#L735-L742

Thanks. Got it

**Review by simonpasquier — APPROVED** [review]

**Comment by simonpasquier** [comment]
Thanks!

**Review by grobinson-grafana — APPROVED** [review]

**Comment by grobinson-grafana** [comment]
Looks good to me! 

```
alertmanager % ./alertmanager --config.file=config.yml --enable-feature auto-gomaxprocs
ts=2024-06-24T08:24:30.883Z caller=main.go:188 level=info msg="Starting Alertmanager" version="(version=0.27.0, branch=support-auto-gomaxproc, revision=2f473f456f8ab59189206f2d8a2ac7934ea1c3e7)"
ts=2024-06-24T08:24:30.883Z caller=main.go:189 level=info build_context="(go=go1.22.4, platform=darwin/arm64, user=grobinson@Georges-Air.fritz.box, date=20240624-08:23:26, tags=unknown)"
ts=2024-06-24T08:24:30.883Z caller=featurecontrol.go:117 level=warn msg="Automatically set GOMAXPROCS to match Linux container CPU quota"
ts=2024-06-24T08:24:30.883Z caller=main.go:200 level=info component=automaxprocs msg="Leaving GOMAXPROCS=8: CPU quota undefined"
```

**Comment by grobinson-grafana** [comment]
Looks good to me!

```
./alertmanager --config.file=config.yml --enable-feature=auto-gomaxprocs
ts=2024-06-24T08:25:41.929Z caller=main.go:188 level=info msg="Starting Alertmanager" version="(version=0.27.0, branch=support-auto-gomaxproc, revision=2f473f456f8ab59189206f2d8a2ac7934ea1c3e7)"
ts=2024-06-24T08:25:41.929Z caller=main.go:189 level=info build_context="(go=go1.22.4, platform=darwin/arm64, user=grobinson@Georges-Air.fritz.box, date=20240624-08:23:26, tags=unknown)"
ts=2024-06-24T08:25:41.929Z caller=featurecontrol.go:117 level=warn msg="Automatically set GOMAXPROCS to match Linux container CPU quota"
ts=2024-06-24T08:25:41.929Z caller=main.go:200 level=info component=automaxprocs msg="Leaving GOMAXPROCS=8: CPU quota undefined"
```

**Pull request merged**
