### PR TITLE
Fixed the future time silencer deletion issue

### PR DESCRIPTION
**Pull request by RSamal**
The delete api not able to delete the Silencer if the startAt is a future time. It was getting below error
ERRO[0030] api error: bad_data: end time must not be before start time  source=api.go:552

Fixed the code in silence.go: Expire

Tested for both active and future silencer and it works fine. Please review and merge

### CODE REVIEW

**Comment by stuartnelson3** [comment]
Hey, It looks like something went wrong with your PR as I'm only seeing a massive amount of deletions. Can you try again after branching from current master?

**Comment by RSamal** [comment]
Hey Stuart,

Thank you. The request was with earlier 0.5 version. I am currently working
out with current master and will create the request.

However I have a question. I do see the logic for GroupKey() in dispatch.go
has been changed from previous branch to current branch.And there are some
other changes in the file also.I dont see any hist log saying why it has
been changed. Do you happen to know about this?

Thanks,
Rama

On May 19, 2017 10:44 AM, "stuart nelson" <notifications@github.com> wrote:

Hey, It looks like something went wrong with your PR as I'm only seeing a
massive amount of deletions. Can you try again after branching from current
master?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/prometheus/alertmanager/pull/617#issuecomment-302767340>,
or mute the thread

**Comment by RSamal** [comment]
Moreover, I don't see these difference when I do a git compare branches.

On Fri, May 19, 2017 at 11:00 AM, Ramakanta Samal <samal.ramakanta@gmail.com

**Comment by RSamal** [comment]
if I do a "gitk dispatch/dispatch.go " I see the last log
"9fcdb47faaae2d79ba640897db78a3296fb57f27" was on 2016-12-06 . But the
current version of this file looks different and there is no revision
history on it.

On Fri, May 19, 2017 at 11:08 AM, Ramakanta Samal <samal.ramakanta@gmail.com
> wrote:

> Moreover, I don't see these difference when I do a git compare branches.
>
> On Fri, May 19, 2017 at 11:00 AM, Ramakanta Samal <

**Comment by RSamal** [comment]
Nevermind I got something on github with log :).  "Turn the GroupKey into a
string that is composed of the matchers if the

path in the routing tree and the grouping labels.
Only hash it at the very end to ensure we don't exceed size limits of
integration APIs."


On Fri, May 19, 2017 at 11:24 AM, Ramakanta Samal <samal.ramakanta@gmail.com
> wrote:

> if I do a "gitk dispatch/dispatch.go " I see the last log "
> 9fcdb47faaae2d79ba640897db78a3296fb57f27" was on 2016-12-06 . But the
> current version of this file looks different and there is no revision
> history on it.
>
> On Fri, May 19, 2017 at 11:08 AM, Ramakanta Samal <

**Pull request closed without merging**
