### PR TITLE
test/cli: add basic amtool cli tests

### PR DESCRIPTION
**Pull request by pgier**
Working on some acceptance tests for amtool

### CODE REVIEW

**Comment by simonpasquier** [comment]
On the first look, it seems ok. I'm pondering whether it would make sense to have these tests live with the other acceptance tests in `test/with_api_v2` as some parts of the code are already common.

**Comment by pgier** [comment]
Originally, I was thinking that these tests would verify backwards compatibility in amtool while making changes like the recent update from v1 to v2.  So for future updates, e.g. if there was ever an api v3, ideally the amtool tests would stay the same and would provide an automated compatibility check.  Although I'm not sure how practical this would be.

**Comment by stuartnelson3** [comment]
any more thoughts on this?

**Comment by mxinden** [comment]
Ping @simonpasquier @pgier.

**Comment by pgier** [comment]
Rebased onto latest master, fixed a merge conflict, and made some minor simplifications.
@simonpasquier can you take a look?

**Pull request merged**
