### PR TITLE
setting favicon.ico dinamically

### PR DESCRIPTION
**Pull request by JBerny**
Refers to #2323

### CODE REVIEW

**Comment by roidelapluie** [comment]
This seems fragile and complex.

Did you try `<link rel="icon" href="favicon.ico" />` (using a relative path?)

**Comment by JBerny** [comment]
> This seems fragile and complex.
> 
> Did you try `<link rel="icon" href="favicon.ico" />` (using a relative path?)

Yeah I thought it was pretty bad too :) 
I didn't know it was an option. I'll try that.

**Comment by simonpasquier** [comment]
LGTM. Can you run `make assets` and commit the changes?

**Comment by JBerny** [comment]
When i run `make assets` i notice that all files api/v2/* are deleted. I didn't think that's ok, so i just commited the changes to asset/assets_vfsdata.go

**Comment by simonpasquier** [comment]
All good, thanks!

**Pull request merged**
