### PR TITLE
Rewrite UI in Elm

### PR DESCRIPTION
**Pull request by mxinden**
As milestone [0.7](https://github.com/prometheus/alertmanager/milestone/4) is done now I would like to propose merging the new ELM-UI into `master`. For further details please see PR #668.

There are still a lot of steps to take, but as far as I can tell it is already a good replacement for the existing Angular-UI.

What do you think? Happy for any feedback.

### CODE REVIEW

**Comment by brancz** [comment]
I spun up an instance, and all looks good to me. One thing that was sort of unexpected is that I had to do a hard refresh because I had previously had a 0.6.2 Alertmanager instance on the same host port combination. As this is a one time thing it's fine, just thought we may want to include it in the release notes.

**Comment by brancz** [comment]
The remaining conflicts are mainly generated and deleted files, so I'd say we manually resolve on merge. lgtm

**Comment by stuartnelson3** [comment]
Assuming the compiled binary runs, I'm good with this. I think from an operational perspective one of the things I would like to do is move compilation + embedding the assets in a go file into a CI step, and not rely on us remembering to do that. But that doesn't prevent this from going out!

:rocket:

**Comment by mxinden** [comment]
@stuartnelson3 I have a PR coming for improving the build process.

**Comment by fabxc** [comment]
Needs a rebase.

**Comment by brancz** [comment]
:tada:

**Pull request merged**
