### PR TITLE
Correctly render continue routing

### PR DESCRIPTION
**Pull request by stuartnelson3**
Nodes with `continue: true` were being ignored,
and only the first match in the routing tree was
being highlighted.

Additionally, each node was incorrectly being set
to continue=true if nothing was received from the
API. The API sends nothing if continue=false (the default).

This change should also be applied to the code in `master`.

See comments for redacted pictures.

### CODE REVIEW

**Comment by stuartnelson3** [comment]
It's difficult to show, so perhaps it would be best to show this to someone in person like @beorn7, but I confirmed that the multi-routing with the `continue` option on a single "catch-all" route works successfully, and the other routes cease the tree search when they don't have `continue: true` in their config.

image

**Comment by beorn7** [comment]
:+1:

**Comment by beorn7** [comment]
Merge into master is not really trivial. I guess we have to cherrypick the change here.

**Comment by stuartnelson3** [comment]
Yes, there's no way to merge into master.

**Pull request merged**
