### PR TITLE
Add Fingerprint to template data

### LINKED ISSUE #1903: Expose alert fingerprint in notification template
Currently the following information is available to the notification template:

```
// Alert holds one alert for notification templates.
type Alert struct {
	Status       string    `json:"status"`
	Labels       KV        `json:"labels"`
	Annotations  KV        `json:"annotations"`
	StartsAt     time.Time `json:"startsAt"`
	EndsAt       time.Time `json:"endsAt"`
	GeneratorURL string    `json:"generatorURL"`
}
```

It would be useful for us to have the fingerprint of the alert as well, for various downstream systems.

### PR DESCRIPTION
**Pull request by kfdm**
Hopefully fixes #1903 by adding the Fingerprint to the template data. My goal for this is to have the fingerprint in the Webhook data for downstream consumption.

### CODE REVIEW

**Comment by kfdm** [comment]
Not sure who is the correct person to ask for a review @simonpasquier  @stuartnelson3
Though seeing there is already a rc planned for 0.18.0 I suppose something like this will need to wait until the following release.

**Comment by kfdm** [comment]
@simonpasquier have you been able to take a look?

**Comment by Paxa** [comment]
Should it be added to docs https://prometheus.io/docs/alerting/notifications/ ?

**Comment by simonpasquier** [comment]
@Paxa yes, feel free to open the PR if you wish.

**Comment by marcusteixeira** [comment]
@simonpasquier I haven't found the path where you reference this alertmanager notification page.
Page: https://prometheus.io/docs/alerting/latest/notifications/

Can you guide me to find it?

**Pull request merged**
