### PR TITLE
Synchronize Makefile.common from prometheus/prometheus

### PR DESCRIPTION
**Pull request by prombot**
Propagating changes from master Makefile.common located in prometheus/prometheus.

### CODE REVIEW

**Comment by stuartnelson3** [comment]
@simonpasquier is that being done in parallel? or added to this pr

**Comment by simonpasquier** [comment]
Added to the PR.

**Comment by SuperQ** [comment]
I created the required repos on quay.io.

**Comment by simonpasquier** [comment]
Thanks a lot @SuperQ!

**Pull request merged**
