### PR TITLE
Show alert annotations

### LINKED ISSUE #821: Display alert annotations
The old UI used to contain current alerts listed by labels with silence buttons, as does the new UI.

To the left of the labels list in the old UI there used to be a Source link with a `+` button. Upon clicking the plus, a "panel" would pop out beneath showing the actual "hydrated" alert text.

The new UI seems to be missing this functionality.

For example, if the alert was `Low Quorom: There's only {{value}} things!` in Prometheus' config view here it would show up as `Low Quorom: There's only 3 things!` if the represented time series' value was 3.

Here's some pictures for a better illustration:

Prometheus example:

prom

0.6 example, with + button already clicked:

0.7 of the same alert, notice there is a Source button but if there is an expander I do not see it :(

### PR DESCRIPTION
**Pull request by w0rm**
Closes  #821

annotations

### CODE REVIEW

**Comment by w0rm** [comment]
Please don't merge yet, I noticed a small issue, will fix before noon.

**Comment by w0rm** [comment]
@mxinden this bindata stuff is annoying. It produces different file locally, even when I pull the latest golang docker and do `docker run --rm -t -v "$(pwd):/usr/src/app" -w /usr/src/app golang make assets`

**Comment by w0rm** [comment]
@stuartnelson3 oh I see. it would be nice if alerts had ids so we didn't have to rely on index

**Comment by stuartnelson3** [comment]
Well, they DO have a unique fingerprint.

@mxinden @fabxc @brancz thoughts on returning the alert's fingerprint from the `/alerts` endpoint?

**Comment by w0rm** [comment]
@stuartnelson3 if we're going to add this field, will it be named `id`? I can mock it in the decoder to be index for now, and then we can use the real value.

**Comment by mxinden** [comment]
Is it possible to finish this PR without adding *id* to the alert object for now? If so, can we move the *AlertID* discussion to this issue #681

**Comment by w0rm** [comment]
@mxinden I think it's fine to enhance alerts with local ids. We will just have to fix the decoder, and it will still work. Please re-review my changes.

**Comment by w0rm** [comment]
If @stuartnelson3 approves, I'd like to ask someone of you to regenerate the bindata, cause I can't make it work.

**Comment by w0rm** [comment]
@stuartnelson3 @mxinden sorry for the misinformation, it was the same problem of updated `elm-test`. I fixed the versions in the Dockerfile and it works now.

**Pull request merged**
