### PR TITLE
CSS changes for readability

### PR DESCRIPTION
**Pull request by jjneely**
Being somewhat visually challenged, I find these changes improve
readability drastically.  This removes some opacity settings, removes
smaller fonts, and address a couple colors.  I now find the native and
more subtle bootstrap mouse overs to be very helpful in locating where
the mouse is with sacrificing being able to read the alerts with a quick
glance.

@fabxc, I'm not a UI designer by any means.

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks, any help is greatly appreciated.
It would be helpful if you could attach screenshots showing the difference for everyone.

**Comment by jjneely** [comment]
Current styling:

am-before

With my changes:

am-after

Minus the horrible obfuscation, of course.

**Comment by fabxc** [comment]
I agree that its more readable but looks pretty raw in some ways. I probably shouldn't make judgements on design – maybe someone else can provide an opinion.

@juliusv @grobie

**Comment by grobie** [comment]
I don't really have an opinion on this change, none of the versions makes me really happy :p I'm not visually impaired when it comes to computer screens, but if it helps others I'm fine with it.

**Comment by fabxc** [comment]
New UI will hopefully fix readability more generally :) Closing here

**Pull request closed without merging**
