### PR TITLE
Enrich templating functions

### PR DESCRIPTION
**Pull request by sylr**
This PR does two things.

First it adds two new functions usable in templates:

 - `split(separator, string) []string`: convert a string to an array of strings
 - `urlEncode(string) string`: convert a string to another usable in URL query parameters

Then it adds a `Select([]string) KV` method on the KV struct.

The goal of all of this is to improve the templates of pagerduty, i.e., selecting only useful labels in the alert description:

```
        pagerduty_configs:
        - routing_key: xxxxxxxxxxxxxxxxxxxxxxxxxx
          details:
            firing: |
              {{ range .Alerts.Firing }}Labels:
              {{ range .Labels.SortedPairs -}}
              - {{ .Name }} = {{ .Value }}
              {{ end }}
              Annotations:
              {{ range .Annotations.SortedPairs -}}
              - {{ .Name }} = {{ .Value }}
              {{ end }}
              Source: {{ .GeneratorURL }}

              {{ end }}
          description: |
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}{{ " " }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              (
              {{- if .CommonAnnotations.alert_title_labels -}}
                {{- $allowed_labels := split "," .CommonAnnotations.alert_title_labels -}}
                {{- with .CommonLabels.Remove .GroupLabels.Names -}}
                  {{- with .Select $allowed_labels -}}
                    {{- .Values | join " " -}}
                  {{- end -}}
                {{- end -}}
              {{- else -}}
                {{- with .CommonLabels.Remove .GroupLabels.Names -}}
                  {{- .Values | join " " -}}
                {{- end -}}
              {{- end -}}
              )
            {{- end -}}
```

If you decide to surprise me for once and merge this I'll make a PR for the documentation.

### CODE REVIEW

**Comment by sylr** [comment]
> This is not necessary

It's certainly isn't but it is a reflection of the frustration resulting from trying to improve your projects (prometheus, alertmanager, client_golanfg) based on real corporate use cases and being almost constantly denied.

**Comment by stuartnelson3** [comment]
>It's certainly isn't but it is a reflection of the frustration resulting from trying to improve your projects (prometheus, alertmanager, client_golang) based on real corporate use cases and being almost constantly denied.

A pull request is not the correct forum for this discussion. If you would like to discuss your frustrations in a constructive manner, I recommend writing to the mailing list.

**Comment by brian-brazil** [comment]
> split(separator, string) []string

The example you give here is a layering violation, alert rules shouldn't decide how they are formatted and what label are important - that's for the alertmanager.

> urlEncode(string) string: convert a string to another usable in URL query parameters

Go templates should be doing this automatically. Is there a case where they aren't?

**Comment by sylr** [comment]
> The example you give here is a layering violation, alert rules shouldn't decide how they are formatted and what label are important - that's for the alertmanager.

So your solution is to make a receiver per alert to have the correct templating ?

**Pull request closed without merging**
