### PR TITLE
Set Pushover notification priority to "emergency".

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by fabxc** [comment]
:+1:

**Comment by Luzifer** [comment]
Cool. Thanks! :+1: Thought this would be more discussion…

**Comment by juliusv** [comment]
@Luzifer Well, now that you made me look at it again, I wonder whether "resolved" notifications should not be emergencies :)

**Comment by Luzifer** [comment]
Good point… Maybe they shouldn't be… :D

**Pull request merged**
