### PR TITLE
Make notification flag names consistent with Prometheus style.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
FYI @a86c6f7964 @discordianfish @brian-brazil

**Comment by brian-brazil** [comment]
:+1:

**Comment by discordianfish** [comment]
Meh, this might break lot of existing setups.. Agree that it should be consistent but I'm neutral on this I guess.

**Comment by juliusv** [comment]
@discordianfish Well, Prometheus itserlf is `0.x` and alertmanager is clearly marked experimental and not production-ready. We'll still have minor breakages like this for a while, but at least they should be noticeable immediately upon startup.

**Pull request merged**
