### PR TITLE
Add basic RocketChat support

### PR DESCRIPTION
**Pull request by korporationcl**
Firstly, and most importantly thank you maintaining this project guys. Secondly, I have created a really basic support to integrate RocketChat alerts. At the moment the only way is using `webhook_config`, which lacks some customisations that we would like to use in order to make our alerting system nicer (templates on Puppet/Hiera).

Thirdly, I went though some old commits in order to figure out how to do this since am not a GoLang developer (not even a developer), I pretty much identified how Slack and Hipchat was implemented and put all the pieces together. 

Finally, I ran the `make format` and `make build-all` locally and seems to passed properly.

### CODE REVIEW

**Comment by korporationcl** [comment]
cc @stuartnelson3 @mxinden

**Comment by simonpasquier** [comment]
Thanks for suggesting this change. Unfortunately, we are currently [not accepting](https://prometheus.io/docs/alerting/configuration/#%3Creceiver%3E) new integrations.

We can only provide the stability and performance we want to provide if we can properly maintain the codebase. This includes, amongst others, test integrations in an automated and scalable fashion. For this reason, we are suggesting people integrate with the help of our generic interfaces. We have an integrations page on which integrations using our generic interfaces are listed.

Even if existing integrations can not be tested in an automated fashion, we will not remove them for reasons of compatibility. This also means that any additions we take on, or any changes to existing integrations we make or accept, will mean maintaining and testing these until at least the next major version, realistically even beyond that.

Feel free to question this answer on our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers), but be aware it's unlikely that you will get a different answer.

**Comment by korporationcl** [comment]
> Thanks for suggesting this change. Unfortunately, we are currently [not accepting](https://prometheus.io/docs/alerting/configuration/#%3Creceiver%3E) new integrations.
> 
> We can only provide the stability and performance we want to provide if we can properly maintain the codebase. This includes, amongst others, test integrations in an automated and scalable fashion. For this reason, we are suggesting people integrate with the help of our generic interfaces. We have an integrations page on which integrations using our generic interfaces are listed.
> 
> Even if existing integrations can not be tested in an automated fashion, we will not remove them for reasons of compatibility. This also means that any additions we take on, or any changes to existing integrations we make or accept, will mean maintaining and testing these until at least the next major version, realistically even beyond that.
> 
> Feel free to question this answer on our [developer mailing list](https://groups.google.com/forum/#!forum/prometheus-developers), but be aware it's unlikely that you will get a different answer.

sure, I appreciate the explanation although I would love to see support for RocketChat in the not too long distant future 👍

**Comment by simonpasquier** [comment]
@korporationcl if you've got already the mechanics in place, it shouldn't be hard to write a standalone service that would receive webhook notifications and forward them to RocketChat. If you get that working, you can then reference your project in the official [documentation](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver).

**Comment by roidelapluie** [comment]
FYI it already exists

https://rocket.chat/docs/administrator-guides/integrations/prometheus/
https://github.com/pavel-kazhavets/AlertmanagerRocketChat

**Comment by korporationcl** [comment]
> FYI it already exists
> 
> https://rocket.chat/docs/administrator-guides/integrations/prometheus/
> https://github.com/pavel-kazhavets/AlertmanagerRocketChat

thank you, yes we are using it actually but I think we can't do things such as templating since the `webhook` resource does offer a very limited amount of options.

**Comment by roidelapluie** [comment]
Indeed templating is the resporibility of the webhook receiver.

**Pull request closed without merging**
