### PR TITLE
Fix a sentence in README

### PR DESCRIPTION
**Pull request by brunoqc**

### CODE REVIEW

**Comment by fabxc** [comment]
This is a [serial comma](http://en.wikipedia.org/wiki/Serial_comma).
While there is no consensus on its usage, we use it consistently in our documentation.

**Comment by juliusv** [comment]
But :+1: for removing the parenthesis :)

**Comment by brunoqc** [comment]
Sorry I didn't know about the serial comma.

I updated the commit.

**Comment by fabxc** [comment]
Great, thanks! :+1:

**Pull request merged**
