### PR TITLE
Revert "Return error when TmplText errors in sns notifier"

### PR DESCRIPTION
**Pull request by gotjosh**
Reverts prometheus/alertmanager#3531

### CODE REVIEW

**Comment by gotjosh** [comment]
@TheMeier this did break the tests - Let's revert it for now until I have some time to figure out what's wrong?

**Review by grobinson-grafana — APPROVED** [review]

**Comment by grobinson-grafana** [comment]
There are two imports for `error` package with the same name:

```go
package sns

import (
	"errors"
	...

	"github.com/pkg/errors"
)
```

```
`errors` redeclared in this block (typecheck)
```

see https://github.com/prometheus/alertmanager/commit/603a72800ed14f94cb20b5561e77df2c54e41d4f.

**Comment by grobinson-grafana** [comment]
We should also replace `errors.Wrap` with `fmt.Errorf` 🙂 @emanlodovice

**Comment by emanlodovice** [comment]
My apologies for the previous PR, it was old and needed to be rebase. I have opened a new PR to fix the issue https://github.com/prometheus/alertmanager/pull/3879/ . Please have a look. Thank you.

**Pull request merged**
