### PR TITLE
Add safeHtml template function.

### PR DESCRIPTION
**Pull request by juliusv**
Fixes https://github.com/prometheus/alertmanager/issues/314

### CODE REVIEW

**Comment by juliusv** [comment]
@brian-brazil Why is this called `safeHtml`, not `safeHTML`, in Prometheus actually? Because it's not a Go function and we apply a different style? Or accident?

**Comment by brian-brazil** [comment]
I forget the reason, I was probably keeping everything camelCase.

**Comment by brian-brazil** [comment]
:+1:

**Comment by juliusv** [comment]
Ok.

**Pull request merged**
