### PR TITLE
*: Cut 0.15.1

### PR DESCRIPTION
**Pull request by mxinden**
Cherry-picking the following bug fixes:

* [BUGFIX] Fix email template typo in alert-warning style (#1421)
* [BUGFIX] Fix regression in Pager Duty config (#1455)
* [BUGFIX] Catch templating errors in Wechat Notify (#1436)
* [BUGFIX] Fail when no private address can be found for cluster (#1437)
* [BUGFIX] Make sure we don't miss the first pushPull when joining cluster (#1456)
* [BUGFIX] Fix concurrent read and wirte group error in dispatch (#1447)

Including version bump and `CHANGELOG.md` entry.

//CC @stuartnelson3 @simonpasquier @brancz

### CODE REVIEW

**Comment by mxinden** [comment]
Mhh, DCO check is failing with `Expected "Guido García <palmerabollo@gmail.com>", but got "Guido García <guido.garciabernardo@telefonica.com>".`

**Comment by mxinden** [comment]
I ran our Prometheus Operator test suit with this patch release. Results can be found [here](https://github.com/coreos/prometheus-operator/pull/1603).

It is failing. I would prefer to investigate the failures tomorrow morning before continuing here. What do you think?

**Comment by mxinden** [comment]
Update: The first Alertmanager instance in a Kubernetes Statefulset of 3 instances is unable to resolve the DNS entries of its peers via a Kubernetes Service at startup, and crash loops. I am further looking into it. I am not sure if this is related to this Alertmanager patch release or just our Prometheus Operator.

**Comment by mxinden** [comment]
Got the issue. I will propose a PR in a little bit.

**Comment by mxinden** [comment]
Fix: https://github.com/prometheus/alertmanager/pull/1465

**Comment by palmerabollo** [comment]
@mxinden I think I signed the [commit](https://github.com/prometheus/alertmanager/pull/1421) with a different email and DCO is complaining. Can I do something to help?

**Comment by brancz** [comment]
Agreed

**Comment by palmerabollo** [comment]
I agree with using my commit here

**Pull request merged**
