### PR TITLE
*: Cut v0.16.0-beta.0

### PR DESCRIPTION
**Pull request by mxinden**
I would like to cut a first beta of Alertmanager v0.16.0. What do you think?

### CODE REVIEW

**Comment by stuartnelson3** [comment]
I would be cool with a beta, would hopefully get more people to use the new UI

**Comment by mxinden** [comment]
I am currently working on transitioning the UI to the new API v2. It still missed a couple of things on the `/status` endpoint. I hope to be done with the transition this week.

I would vote for holding off with this PR until the transition is done. Not a strong opinion. What are your thoughts?

**Comment by stuartnelson3** [comment]
It would be nice to use the new API so we can get a feel for it and maybe write some guidance on generating clients. I think waiting to transition makes sense.

**Comment by stuartnelson3** [comment]
It's probably about time to get this moving along :)

Any prediction on when https://github.com/prometheus/alertmanager/issues/1627 will be addressed?

**Comment by simonpasquier** [comment]
@stuartnelson3 i'll give #1627 a stab today.

**Comment by mxinden** [comment]
@stuartnelson3 I still need to move the alerts page of the UI over to the new API. I should have a pull request up by tomorrow. I would like to wait for that patch to merge before cutting the first release.

Would that be ok for you @stuartnelson3 and @simonpasquier?

**Comment by mxinden** [comment]
I have created a milestone (https://github.com/prometheus/alertmanager/milestone/6) for the upcoming release. From my side there are only two minor fixes on the agenda. Anything I am missing?

Once that is merged I will continue here and cut the first beta or alpha.

**Comment by roidelapluie** [comment]
@mxinden #1588 seems ready too

**Comment by mxinden** [comment]
@roidelapluie #1588 is merged now. Thanks for the hint.

I will update the changelog next.

**Comment by mxinden** [comment]
Replaced by https://github.com/prometheus/alertmanager/pull/1646.

**Pull request closed without merging**
