### PR TITLE
Display connections in the Status page

### PR DESCRIPTION
**Pull request by simonpasquier**
Relates to #625.

## _Mesh status with 2 nodes and one being down_

image

## _Same cluster with the 2 nodes up_

image

### CODE REVIEW

**Comment by brancz** [comment]
lgtm, @stuartnelson3 should probably glance over the elm parts

**Comment by stuartnelson3** [comment]
Interesting, have you seen the state leave `pending`? The alertmanagers are definitely gossiping silences, but the status is never transitioning from `pending` to `established`. Interesting.

**Comment by simonpasquier** [comment]
Thx @stuartnelson3! Indeed I've spotted the `pending` state but since the info comes from the mesh library and @brancz said that the lib might be replaced eventually, I didn't investigate further.

**Comment by brancz** [comment]
Still worth an investigation I would say, replacing weaveworks/mesh is a big task, it will take a long time.

**Pull request merged**
