### PR TITLE
Update for new HA docs

### PR DESCRIPTION
**Pull request by jamtur01**
Quick fix to #1275.

### CODE REVIEW

**Comment by starsdeep** [comment]
Seems there is no "--cluster.peer-id" or "--cluster.nickname" flag ? Then, what's the peer name/id of a AlertManager instance ?

**Comment by starsdeep** [comment]
Oh, I see. "--cluster.peer" flag accept peers' ip address

**Comment by brancz** [comment]
lgtm

**Comment by jamtur01** [comment]
@stuartnelson3 Done.

**Pull request merged**
