### PR TITLE
feat: support dingtalk notification

### LINKED ISSUE #665: add dingding support in alertmanager
Dingding is the most popular communicate tool in China like slack, but altermanager doesn't support send message to dingding robort(webhook doesn't match format in dingding ), i'd like to PR this function like slack

### PR DESCRIPTION
**Pull request by halfcrazy**
DingTalk is a Chinese enterprise IM. Integrated DingTalk via webhook description at https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.2aYysA&treeId=257&articleId=105735&docType=1

FIX #665

### CODE REVIEW

**Comment by simonpasquier** [comment]
As you can read in the [Prometheus documentation](https://prometheus.io/docs/alerting/configuration/#%3Creceiver%3E), the project doesn't accept new receivers. In case you didn't know already, there's an existing webhook to DingTalk project: https://github.com/timonwong/prometheus-webhook-dingtalk

**Comment by xizhibei** [comment]
Hi, @simonpasquier, I would like to request you to accept this PR. (Actually I am also developing my own version[1], but this one also works)

First, as @berlinsaint said in  https://github.com/prometheus/alertmanager/pull/1059:
> Wechat In Chinese have a huge number users. Not Every users know webhook or implement the webhook notification. I strongly recommend to merge this contribute. All the notifier's in alertmanger now is never used in chinese .BTW i think alertmanger will get more users in chinese, this is good things ,right?

DingTalk[2] is the main competitor to Wechat Corp Version  (And maybe DingTalk is the No.1 ), and Dingtalk already reachs users to 100 million[3]. There is no reason you accept WechatCorp but not for Dingtalk. You accept the PR, you gain 80%(or maybe more) of Chinese users.

Second, the "prometheus-webhook-dingtalk" is not convenient for developer to setup, since it is a independent component and It is facing the high available problem, we have to deploy at least 3 of it, which increasing the complexity to deploy. Accept this PR, you do great help to Chinese Developers, thanks in advance :P

And last, I understand your concerns about too many receivers will make alertmanager hard to maintain, so if you still not  accept this PR, would you like to consider develop plugin system, so that we can easily add any receivers ？

[1]. https://github.com/xizhibei/alertmanager/tree/dingtalk-notify
[2]. https://www.dingtalk.com/en/download
[3]. https://medium.com/dingtalk/dingtalk-a-product-by-alibaba-reaches-100-million-users-ee693d381734

**Comment by brian-brazil** [comment]
> if you still not accept this PR, would you like to consider develop plugin system, so that we can easily add any receivers ？

The webhook is the plugin system.

**Comment by xizhibei** [comment]
Thanks for reply, but I mean the plugin system like the one in [elastalert](https://github.com/Yelp/elastalert): https://elastalert.readthedocs.io/en/latest/recipes/adding_alerts.html, you write your own code, integrated in one process, and  easy to deploy.

**Pull request closed without merging**
