### PR TITLE
support loading webhook URL from a file

### PR DESCRIPTION
**Pull request by sr**
Both [DeadMansSnitch](https://deadmanssnitch.com) and [Healthchecks.io](https://healthchecks.io) treat the URL as a secret, so I am guessing this is a common enough use case.

/cc #2498

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
lgtm. @gotjosh are you fine with this change? It's a bit puzzling that the `url` field isn't a secret type but changing it would be inconvenient for many users and the `url_file` field fills a gap for some webhooks.

**Comment by sr** [comment]
AFAICT the only place where it's marshalled back is in the status page. So changing `WebhookConfig.URL` to be a `SecretURL` would cause it be shown as the string "<secret>", vs then the actual URL now.

Side note, if it were to changed to a secret, `notify.RedactURL(err)` would be needed here: https://github.com/prometheus/alertmanager/blob/f59460bfd4bf883ca66f4391e7094c0c1794d158/notify/webhook/webhook.go#L106

**Comment by sr** [comment]
@gotjosh @simonpasquier Should I make the SecretURL change here or in a separate PR?

**Comment by gotjosh** [comment]
Can you please put together a separate PR? Thanks @sr.

**Comment by sr** [comment]
Sweet, thanks for merging https://github.com/prometheus/alertmanager/pull/3228.

I've merged in main and added a few more tests, including a couple test cases I should have added in https://github.com/prometheus/alertmanager/pull/3200.

`make test` is passing locally. The failure on CI looks like a flake:
https://app.circleci.com/pipelines/github/prometheus/alertmanager/3322/workflows/6647f932-9964-42fc-9291-f0e1f560254c/jobs/14718

**Comment by sr** [comment]
@simonpasquier Build is now green. Good merge?

**Review by simonpasquier — APPROVED** [review]

**Comment by simonpasquier** [comment]
thanks!

**Comment by aned** [comment]
Is it possible to have one secrets file with multiple `receiver_name: api_url`, so the alertmanager can parse it based on the `receiver_name` instead of having many files?

**Pull request merged**
