### PR TITLE
chore: use HumanizeTimestamp from prometheus/common

### PR DESCRIPTION
**Pull request by freak12techno**
Adding HumanizeDuration from prometheus/common (moved it there in this PR: https://github.com/prometheus/common/pull/654).
Also copy-pasted some test cases from Prometheus repo.

### CODE REVIEW

**Comment by freak12techno** [comment]
@gotjosh since it was you who reviewed my last PR here, can you check or ask someone to do so?

**Comment by freak12techno** [comment]
Seems like the test failing is not mine and should've been caused by my PR right?

**Comment by simonpasquier** [comment]
Thanks for PR! I believe that the PR should be retitled "chore: use HumanizeTimestamp from prometheus/common". Also please add the new `humanizeTimestamp` function to docs/notifications.md.

I'm not quite sure where someone would have the opportunity to use the function in Alertmanager templates?

**Comment by freak12techno** [comment]
@simonpasquier thanks for noticing the PR naming, I updated it. On docs, will also add it a bit later.
For usage, I personally have some alerts that expose unix timestamp as a value, would be nice to be able to format it in a nice way.

**Comment by freak12techno** [comment]
@simonpasquier fixed the docs as well

**Comment by simonpasquier** [comment]
> For usage, I personally have some alerts that expose unix timestamp as a value, would be nice to be able to format it in a nice way.

Got it but the value shouldn't be present in the data accessible to the Alertmanager templates. Or am I missing something?

**Comment by freak12techno** [comment]
@simonpasquier actually yes, haven't thought of that. Do you think it'll be still useful or if I should close it?

**Comment by simonpasquier** [comment]
I wouldn't add the function until we have a use case (otherwise it creates unnecessary load for users and maintainers).

**Comment by freak12techno** [comment]
Gotcha, I'll close it then. Will re-add if there's a usecase for it later.

**Pull request closed without merging**
