### PR TITLE
Docs: target_match and source_match are DEPRECATED

### PR DESCRIPTION
**Pull request by 7olstoy**
Via original docs https://prometheus.io/docs/alerting/latest/configuration/#inhibit_rule

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks! This does  not use the new matcherc, in the form of severity=warning etc.

**Comment by 7olstoy** [comment]
@roidelapluie Well, I guess we need a new one sample with not deprecated syntax. You can correct me, if I wrong.
This is the main reason why I opened PR.

**Comment by roidelapluie** [comment]
yes, but this is an example with a mix between the old and the new syntax.

**Comment by 7olstoy** [comment]
@roidelapluie yeah, my bad. I just have looked at my working config. Check it.

**Comment by roidelapluie** [comment]
Thanks!

**Pull request merged**
