### PR TITLE
fix bug:The silence rule does not work in some situations

### PR DESCRIPTION
**Pull request by waitstory**
When the state of the created silence rule is pending,
the silence rule cannot be silent alert.For this change,
I validated it ensure that the function of the system is
not affected system.

### CODE REVIEW

**Comment by beorn7** [comment]
Hi @waitstory , thanks for your contribution. Your description is hard to understand. I tried to find out what bug you are addressing here, and I think it is the following:

If a silence is pending, i.e. it is created with a start date in the future, and then we do not create new silences, we'll never notice when the silence becomes active.

However, I don't think your fix fixes all possible ways the problem can occur. It only works if there are no IDs, but if old IDs exist, but they are all expired by now, you would still run into the same problem. Also, your approach nullifies the whole point of versioning the silence state, which is that we don't have to run a full query each time we call the method.

Maybe a better approach would be to not only save the IDs fur currently active silences but also separately for pending silences so that we check those even if the version of the silences did not change.

The best starting point is to create a unit test that exposes the bug.

**Comment by beorn7** [comment]
I think what we discuss here causes #2426 .

**Comment by waitstory** [comment]
The problem I've encountered is creating a silence rule that takes effect at a future time, and there are no silent matching alerts.
Take the following case, When the current time is "02:03:11, 2021-05-19 (UTC)", create a silence rule starting with the time "02:05:29, 2021-05-19 (UTC)".The state of silence rule is "pedding".But creating this silence rule does not silently match alerts within the time range in which it is in effect.That's a real problem.
image

**Comment by beorn7** [comment]
Yes, that's precisely the problem I tried to understand. And yes, that's a real problem.
However, as said, I don't think you code fixes the problem properly, and at the same time it still defeats the whole purpose of versioning.

As said, I think we need to track pending silences affecting an alert in the future separately.

And as also said, the first step would be to create a unit test exposing the problem.

Do you think you could create such a unit test?

**Comment by waitstory** [comment]
I think it's hard to do a unit test to expose the bug. Also, I would like to ask when this problem will be fixed. This problem is in the use of the process will appear the problem.

Besides, I don't quite understand the meaning of this sentence—"I think we need to track pending silences affecting an alert in the future".

**Comment by beorn7** [comment]
I can probably best explain it by actually fixing the issue. I'll try as soon as possible.

It is, indeed, a bug hard to fix. And the unit test is probably quite involved, too. And yes, I agree we need to fix this, it's a rather nasty bug.

So if anyone with intimate knowledge of this codebase could beat me to fixing this, even better.

**Comment by beorn7** [comment]
OK, I hacked together #2590. Still needs testing.

**Comment by beorn7** [comment]
I have now created a test case exposing the problem and a working fix in PR #2590.

Therefore, I'm closing this. @waitstory , many thanks for your attempt. It made me aware of the issue and enabled me to create the fix in #2590.

**Pull request closed without merging**
