### PR TITLE
Add /-/reload endpoint #353

### PR DESCRIPTION
**Pull request by ZhenyangZhao**
I had added "api/-/reload" endpoint to reload configuration file like prometheus server.
Hope my contribute can be used.
Thanks all.

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks! It's not quite there yet. You have to modify the part in `main.go` to make use of the `API.Reload()` channel. You can check how prometheus/prometheus does it for reference.

**Comment by ZhenyangZhao** [comment]
@fabxc  Thanks for reply me. Did you mean to add the code like the prometheus server?

// Wait for reload or termination signals.
// Unblock SIGHUP handler.
close(hupReady)

**Comment by fabxc** [comment]
Yes, we should have the `hupReader` functionality as well.
In particular I was talking about [this line](https://github.com/prometheus/prometheus/blob/master/cmd/prometheus/main.go#L134) which is necessary so that the reload channel from the API handler actually triggers a reload.

**Comment by ZhenyangZhao** [comment]
@fabxc Thank you very much.I have learn so much knowledge.

Best Regards.

**Comment by fabxc** [comment]
Thanks, can you run `make format` submit the changes and then squash all your commits?

**Comment by ZhenyangZhao** [comment]
@fabxc sure :)

**Pull request closed without merging**
