### PR TITLE
Add api/-/reload endpoint #353

### PR DESCRIPTION
**Pull request by ZhenyangZhao**
Add api/-/reload endpoint #353 

@fabxc  Sorry for re-created the pull request. Because i cant fix the git conflict.

Thanks

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks 👍

**Comment by juliusv** [comment]
Was it intentional that the path is `/api/-/reload` in AM, whereas Prometheus has the same under `/-/reload`?

**Comment by ZhenyangZhao** [comment]
@juliusv Thankyou very much.  I add  this  reload  endpoint under the path "api/" in alertmanager,because i found almost all the alertmanager's api are under 'api/' path  not the root path like prometheus.

**Comment by fabxc** [comment]
It should be the root path like Prometheus

**Comment by juliusv** [comment]
Ok, I opened a PR to move it: https://github.com/prometheus/alertmanager/pull/376

**Comment by ZhenyangZhao** [comment]
@fabxc @juliusv   :+1: thanks

**Pull request merged**
