### PR TITLE
*: configure http client from config

### LINKED ISSUE #516: Webhook: allow setting TLS options (ca cert, possibly client certs) and Auth Bearer token
It would be great to support setting tls options and support authentication for webhooks.

### PR DESCRIPTION
**Pull request by simonpasquier**
This is #930 rebased on master.

Closes #516 and #853.

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/alertmanager/1222)

### CODE REVIEW

**Comment by brancz** [comment]
@brian-brazil are we ok with going forward with this?

**Comment by brian-brazil** [comment]
This seems fine, just needs the config regession tests extended and an additional test that we're not leaking say the basic auth secret on the config status page wouldn't hurt either.

**Comment by simonpasquier** [comment]
@brian-brazil ack. I'll give a shot at the docs too.

**Comment by simonpasquier** [comment]
@brancz @brian-brazil PTAL

**Comment by brancz** [comment]
The docs PR seems to have a pending comment, otherwise this lgtm

**Comment by brian-brazil** [comment]
:+1:

**Comment by simonpasquier** [comment]
@brancz regarding the docs, @brian-brazil said that they are fine now.

**Pull request merged**
