### PR TITLE
Add insecure_skip_verify to skip TLS verification

### PR DESCRIPTION
**Pull request by AndreaGiardini**
Hello!

I added the `insecure_skip_verify` option to skip TLS verification. The same option is present already in prometheus. I tried the patch and it seems to work correctly.

First time go contributor, waiting for feedback :)

### CODE REVIEW

**Comment by brancz** [comment]
There are some efforts to get all the HTTP configurations into Alertmanager, but there was some contention around it, so I'm hoping we can resolve that soon and finally have them. I don't think this will be necessary then.

**Comment by brian-brazil** [comment]
This PR is about SMTP, not HTTP. We already have a setting for not requiring TLS, do we really need this? An SMTP server presenting an invalid cert seems odd.

**Comment by AndreaGiardini** [comment]
In my case I need to send email to the SMTP server using an ssh tunnel (I can't connect directly from the k8s cluster to the mailserver). The mailserver requires tls, but alertmanager complains about the certificate since i am using a different hostname.

**Comment by AndreaGiardini** [comment]
Can I have an update on this pull request?

As said above, from GCP is impossible to reach external mail services (except very few, but for example office365 is not included) so i need to forward emails using a proxy service.
The mail certificate shown is valid for the office365 domain, but not for our internal k8s service. This is why we need this patch in alertmanager.

**Comment by brancz** [comment]
Looks like it's been picked up again, with the full config: https://github.com/prometheus/alertmanager/pull/1222

**Comment by AndreaGiardini** [comment]
Does it include also smtp? It doesn't look like to me...

**Comment by brancz** [comment]
This is embarrassing ... :facepalm: don’t mind me, I’m still in post fosdem recovery.

**Comment by ramonskie** [comment]
any update on this?

**Comment by AndreaGiardini** [comment]
@ramonskie I can rebase it and resolve the conflicts, but I would like to understand from one of the maintainers if they intend to merge this feature or not. I see several people interested in this.

**Comment by ramonskie** [comment]
@AndreaGiardini i thought this was for amtool.
but at a closer look it seems that this is not the case

**Comment by c0ff3e** [comment]
Hi,  this is something i need.
as we run a internal DNS and none public CA.

**Pull request closed without merging**
