### PR TITLE
autorefresh Alertmanager UI every minute

### PR DESCRIPTION
**Pull request by Hayk96**
Allow Alertmanager to refresh every minute, to keep alerts up to date.

### CODE REVIEW

**Comment by SuperQ** [comment]
Sorry, this would cause sudden reloads while a user is editing a silence. This would be very bad.

**Comment by Hayk96** [comment]
I agree with you. Thank you!
p.s. Having an auto-refresh feature will be good.

**Comment by roidelapluie** [comment]
Most browsers have plugins to enable auto-refreshing a tab.

**Comment by SuperQ** [comment]
Doing refersh via the javascript UI would probably be better, this way users can toggle it, and the UI can block refersh when editing.

**Comment by Hayk96** [comment]
You're right @SuperQ, that's will be better.

**Pull request closed without merging**
