### PR TITLE
Negative matchers on the Silence form page

### LINKED ISSUE #1682: Allow negative (re) matching in silences
Similar to https://github.com/prometheus/alertmanager/issues/1023, but for silences.

Currently you can only have `=` and `=~` matchers in silences. I recently wanted to silence all jobs from a given Prometheus server *except* for some specific ones, and being able to do a negative regex match would have been useful there, especially since RE2 doesn't support negative lookaheads.

### PR DESCRIPTION
**Pull request by w0rm**
Closes #1682

This implements the ability to create silences with negative matchers using the UI element from the alerts page.

Screenshot 2021-02-20 at 13 26 58

Signed-off-by: w0rm unsoundscapes@gmail.com

### CODE REVIEW

**Comment by beorn7** [comment]
Great. Will have a closer look ASAP.

**Comment by beorn7** [comment]
Awesome. I cannot judge the Elm code, but I played with it, and it does what it should do. Let's see if @simonpasquier or anyone with Elm foo wants to chime in (for another day or so), but otherwise, I think we should just merge this.

**Review by beorn7 — APPROVED** [review]

**Comment by beorn7** [comment]
@vladimiroff you might be interested in this, too.

**Review by vladimiroff — APPROVED** [review]
Looking good. Also, edit and recreate forms don't forget `isEqual`, which is something I've spent a lot more time, that I am willing to admit. Extra points for the proper cleanup in `SilenceForm/Types.elm`, taught me a lot.

**Pull request merged**
