### PR TITLE
Alertmanager: Add Microsoft Teams Webhook notification.

### PR DESCRIPTION
**Pull request by Myslik**
This adds notifications to Microsoft Teams. It is using the Webhook connector. Let me know what you think.

It should be simple as this
```
receivers:
- name: teams-receiver
  teams_configs:
    - webhook_url: https://outlook.office.com/webhook/[REDACTED]
```

### CODE REVIEW

**Comment by mxinden** [comment]
We're not adding any more receivers to AlertManager (see [doc](https://prometheus.io/docs/alerting/configuration/#receiver)). You could implement a custom binary via the Alertmanager [webhook](https://prometheus.io/docs/alerting/configuration/#webhook_config) receiver. Once that project exists we are happy to list it on the [integrations](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver) page.

I am sorry that we can't accept your work here. To prevent this from happening in the future, please open a Github issue prior to working on a feature so that we can discuss it beforehand.

**Comment by Myslik** [comment]
@mxinden Are direct integrations to be phased out in the future? Is webhook receiver preferred approach?

**Comment by simonpasquier** [comment]
Yes the webhook receiver is the recommended way to integrate 3rd-party systems with AlertManager. In case you aren't aware of it, https://github.com/idealista/prom2teams already does this.

**Comment by Myslik** [comment]
Thanks for info

**Comment by mxinden** [comment]
There is no decision in regards to what should happen with the existing integrations. We are not accepting new ones due to the maintenance burden this putts on the maintainers.

Yes, the webhook receiver is the preferred approach.

**Pull request closed without merging**
