### PR TITLE
nflog: Fix Log() crash when gossip is nil

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by brancz** [comment]
Just to understand the circumstances of this, as there is no description or issue, I'm assuming this happened, when one turns off the mesh of Alertmanager?

**Comment by juliusv** [comment]
@brancz Right, sorry for the missing context. Alertmanager crashed on me when running it without mesh enabled (`-mesh.listen-address=`).

**Comment by brancz** [comment]
Thanks, just wanted to make sure we're not just masking an underlying problem :)

**Comment by giganteous** [comment]
Starting up with an empty mesh is now solved, interrupting the process still gives a panic:

```
^Clevel=info ts=2017-11-03T21:33:12.583129394Z caller=main.go:393 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2017-11-03T21:33:12.58334731Z caller=nflog.go:287 component=nflog msg="Running maintenance"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x84dc92]

goroutine 1 [running]:
github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh.(*Router).Stop(0x0, 0xc4200001a8, 0xc42006dab0)
	/home/kai/src/github.com/prometheus/alertmanager/vendor/github.com/weaveworks/mesh/router.go:92 +0x22
main.main.func4(0xc420098240, 0x0, 0xc4200968e0)
	/home/kai/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:242 +0x39
main.main()
	/home/kai/src/github.com/prometheus/alertmanager/cmd/alertmanager/main.go:394 +0x1a7d
```

Version:
```sh
quadraginta:...com/prometheus/alertmanager (master) $ ./alertmanager -version
alertmanager, version 0.9.1 (branch: master, revision: 029c70d6fe0c594a16d539bac8ec8782d2273869)
  build user:       kai@quadraginta
  build date:       20171103-21:25:19
  go version:       go1.9.1
```
So, further down the stack, the gossip is stopped it seems. I'm unfamiliar with the internals.

**Comment by juliusv** [comment]
Indeed, https://github.com/prometheus/alertmanager/pull/1078 should fix
this. Thanks for reporting.

**Pull request merged**
