### PR TITLE
fix for Issue 287 (https://github.com/prometheus/alertmanager/issues/…

### PR DESCRIPTION
**Pull request by zwopiR**
a proposal for https://github.com/prometheus/alertmanager/issues/287 to be discussed

### CODE REVIEW

**Comment by brian-brazil** [comment]
We should be fixing this for all notifiers over in ExecuteTextString, rather than just for opsgenie.

**Comment by zwopiR** [comment]
@brian-brazil here is a proposal that fixes #287 as well as similar cases in other notifiers. Can you help me with the failing test? I can't reproduce it here on my machine

**Comment by fabxc** [comment]
Thanks :+1: 

Restarted the tests. The acceptance tests are unfortunately very flaky on the low resources CI provides.

**Comment by zwopiR** [comment]
Thanks fabxc

**Comment by brian-brazil** [comment]
This is a general resilience and usability change, so we'll take this one anyway. Thanks!

**Pull request merged**
