### PR TITLE
Return error when TmplText errors in sns notifier

### LINKED ISSUE #3528: SNS notifier swallows errors related to missing templates used in the config
**What did you do?**
When the sns configuration has attributes referencing templates that does not exist Notify will fail but the error says that its because the topic_arn is blank.

Error message:
```
Invalid parameter: TopicArn Reason: An ARN must have at least 6 elements, not 1
```

**What did you expect to see?**
When the sns configuration has attributes referencing templates that does not exist the error should tell me that Notify failed because of this missing template, not something about the topic_arn.

* Alertmanager configuration file:
```
    - name: 'test'
      sns_configs:
        - topic_arn: "arn:aws:sns:us-west-2:123456:TestTopic"
          send_resolved: false
          sigv4:
            region: "us-west-2"
          attributes:
            tags: '{{ template "__unknown_template" .Alerts.Firing }}'
```

### PR DESCRIPTION
**Pull request by emanlodovice**
Update sns notifier to return the error that `TmplText` returns instead of completely ignoringg it

Fixes #3528

### CODE REVIEW

**Review by qinxx108 — APPROVED** [review]

**Comment by emanlodovice** [comment]
@gotjosh good day, can you have a look at this fix? Thank you

**Comment by emanlodovice** [comment]
oops, just realized that this template error is classified as `other` in the error metric, going to it to be classified as `clientError`

**Comment by emanlodovice** [comment]
updated

**Review by LeviHarrison — APPROVED** [review]
LGTM, thanks!

**Comment by TheMeier** [comment]
This did break the tests:
```
notify/sns/sns.go:32:2: missing go.sum entry for module providing package github.com/pkg/errors (imported by github.com/prometheus/alertmanager/notify/sns); to add:
        go get github.com/prometheus/alertmanager/notify/sns
```
https://app.circleci.com/pipelines/github/prometheus/alertmanager/5173/workflows/a1d2baef-4384-4617-a4b5-8c3c451a9a0f/jobs/22363

If you add the package and update go.mod and go.sum locally tests fail with:
```
# github.com/prometheus/alertmanager/notify/sns
notify/sns/sns.go:32:2: errors redeclared in this block
	notify/sns/sns.go:18:2: other declaration of errors
notify/sns/sns.go:32:2: "github.com/pkg/errors" imported and not used
notify/sns/sns.go:120:74: undefined: errors.Wrap
notify/sns/sns.go:155:74: undefined: errors.Wrap
notify/sns/sns.go:162:75: undefined: errors.Wrap
notify/sns/sns.go:179:75: undefined: errors.Wrap
notify/sns/sns.go:187:75: undefined: errors.Wrap
notify/sns/sns.go:193:74: undefined: errors.Wrap
notify/sns/sns.go:210:75: undefined: errors.Wrap
```

**Pull request merged**
