### PR TITLE
Fix config name inconsistency

### PR DESCRIPTION
**Pull request by josedonizetti**
This PR renames configuration from 3 different notifiers to make it consistent with others. Basically, global configurations will be named `<notifier>_api_url`, and local configurations per notifier `api_url`. 

This are **breaking changes**.

Fixes https://github.com/prometheus/alertmanager/issues/680 and https://github.com/prometheus/alertmanager/issues/875

@stuartnelson3 @brancz @brian-brazil @juliusv

### CODE REVIEW

**Comment by brian-brazil** [comment]
We've generally followed the name that the provider uses in their docs when it comes to these things, as a user cares about only 1 of these which they already know - not that they're consistent across the alertmanager.

 Do these all match up with that?

**Comment by brancz** [comment]
I wonder how much it's worth breaking these, as I'm pretty sure _a lot_ of configurations are going to break when people upgrade to these changes.

**Comment by josedonizetti** [comment]
@brian-brazil I've changed the PR to rename only two configs:

- `hipchat_url` to `hipchat_api_url`, this fixes https://github.com/prometheus/alertmanager/issues/875 and checking the hipchat documentation the term 'API' does match more than just 'URL'

- `opsgenie_api_host` to `opsgenie_api_url`, this fixes https://github.com/prometheus/alertmanager/issues/680, the opsgenie documentation does not use the term 'host' but 'API' and 'URL'

**Comment by josedonizetti** [comment]
@brancz Yup, agree that it will break. My idea when I first send this PR was to have it merged for the version **0.10.0**, was considering at the time that the first double number in the version would be a good moment to such a break.

But i totally understand if you think that is not worth, let's just add a note about it on the issues so no other PR is created for it for now, maybe in a future 1.0 release the break might make more sense.

**Comment by brancz** [comment]
> in a future 1.0 release

I think this would be more appropriate. Similar breaking re-namings were done from Prometheus 0.x to 1.x.

**Comment by brian-brazil** [comment]
I don't think that this is a breaking change in practice, as these settings should ~never need to be changed from the defaults by users.

**Comment by aecolley** [comment]
You lose a karma point for this because my employer's private HipChat server means that this was a setting that most definitely needed to be different from the default.

**Comment by stuartnelson3** [comment]
Thank you for bringing that to my attention. I was not aware hipchat could be run privately.

**Pull request merged**
