### PR TITLE
*: Cut 0.15.0 merge to master

### PR DESCRIPTION
**Pull request by mxinden**
Signed-off-by: Max Leonard Inden <IndenML@gmail.com>

Follow up for https://github.com/prometheus/alertmanager/pull/1429

//CC @simonpasquier @stuartnelson3 @brancz @grobie

### CODE REVIEW

**Comment by grobie** [comment]
:+1: I think you could also have just created a PR from `prometheus:release-0.15` to `prometheus:master`, but should be the same in the end.

**Comment by roman-vynar** [comment]
The release notes https://github.com/prometheus/alertmanager/releases/tag/v0.15.0 do not say anything about breaking changes when upgrading from `0.14.0` :(

1. Previously, the work dir was `/alertmanager`
Now it is `/etc/alertmanager `
This is important when you mount a storage dir to the docker container.

2. `--mesh.listen-address` is renamed to `--cluster.listen-address` and added a bunch of other --cluster.*

```
     command: >
       --web.listen-address=127.0.0.1:9093
-      --mesh.listen-address=
+      --cluster.listen-address=
     volumes:
-      - /data/alertmanager:/alertmanager
+      - /data/alertmanager:/etc/alertmanager/data
```

**Comment by grobie** [comment]
@roman-vynar all the the items marked as `[CHANGE]` are breaking changes. The changes to the workdir are indeed not mentioned there though.

**Comment by mxinden** [comment]
@roman-vynar Thanks for trying out the release so quickly. My bad, thanks for reporting that.

Let me know what you think of https://github.com/prometheus/alertmanager/pull/1432 as a follow up.

I will continue here, and have https://github.com/prometheus/alertmanager/pull/1432 address your comments.

**Comment by mxinden** [comment]
> +1 I think you could also have just created a PR from prometheus:release-0.15 to prometheus:master, but should be the same in the end.

@grobie right :smile: next time.

**Pull request merged**
