### PR TITLE
upgrade client_golang to v9.4 and integrate interface changes

### PR DESCRIPTION
**Pull request by carlfriedrichgauss**

### CODE REVIEW

**Comment by stuartnelson3** [comment]
@beorn7 if you have a minute, can you double check the changes to the client code are correct?

**Comment by beorn7** [comment]
The API client in general and the recent changes in particular are not exactly my area of expertise. @krasi-georgiev would be the person to ask.

**Comment by simonpasquier** [comment]
With regards to the client code, the changes look ok. :+1:

**Comment by krasi-georgiev** [comment]
seems that the Warning error interface I suggested doesn't work very well for @jacksontj use case so I would say hold the go client changes for now.
https://github.com/prometheus/client_golang/pull/599

**Comment by krasi-georgiev** [comment]
new changes merged so can either update to the  un-versioned commit or wait for the next release.

**Comment by stuartnelson3** [comment]
thanks @krasi-georgiev. I vote we wait for the next release, if that's ok with folks.

**Comment by beorn7** [comment]
I plan to release client_golang v1 today! :tada:

**Comment by mxinden** [comment]
Closing in favor of https://github.com/prometheus/alertmanager/pull/1926/.

**Pull request closed without merging**
