### PR TITLE
Replace satori/go.uuid with gofrs/uuid

### PR DESCRIPTION
**Pull request by codesome**
github.com/satori/go.uuid seems to have some fixes/enhancement since it's last tagged release. And it has been a while since it had any commit into master (last was Oct 2018), so I am not expecting a tagged release to be out anytime soon.

So I am proposing we upgrade it to master (it is also blocking other upgrades in grafana/grafana).

EDIT: replaced the package based on suggestion here https://github.com/prometheus/alertmanager/pull/2511#issuecomment-795419514

### CODE REVIEW

**Review by gouthamve — APPROVED** [review]
LGTM!

**Review by beorn7 — APPROVED** [review]
OK as band aid. But preferably, we avoid those hacks.

Have you tried to ping the maintainers of the upstream repository about tagging a version?

**Comment by roidelapluie** [comment]
We could also move to a maintained fork, https://github.com/gofrs/uuid

**Comment by beorn7** [comment]
That sounds like a plan!

**Comment by codesome** [comment]
I have now replaced satori/go.uuid with gofrs/uuid, PTAL

**Review by beorn7 — APPROVED** [review]
And wow, TIL that github.com/gofrs/uuid has reverted their Go Modules support ("until Go Modules is more mature").

**Pull request merged**
