### PR TITLE
Cut release 0.8.0

### PR DESCRIPTION
**Pull request by beorn7**
Since @mxinden doesn't seem to be available right now, and I cannot push to the branch in his GH account, I have recreated #906 with the correct release date and rebased on top of master.

@stuartnelson3 @w0rm

### CODE REVIEW

**Comment by beorn7** [comment]
I take the thumbs on #906 as valid for this one, too.

**Comment by stuartnelson3** [comment]
Them thumbs be valid.

Godspeed.

**Comment by mxinden** [comment]
@beorn7 I am sorry for taking so long with the release. Thanks for moving on, appreciate the help. Sorry for the trouble.

**Comment by beorn7** [comment]
@mxinden No worries at all. Given my current job constraints, it actually makes me quite happy if my job needs and my activity here aligns nicely...

**Pull request merged**
