### PR TITLE
config: fix regression with Pager Duty

### LINKED ISSUE #1451: 0.15.0 Overwriting defaults in pagerduty_configs details broken
Hi this is a problem I experienced when trying to update to 0.15.0

**What did you do?**
I ran `alertmanager-0.15.0.linux-amd64/amtool --alertmanager.url example.com check-config /usr/local/example.yml`

**What did you expect to see?**
I expected to get the same output as with `alertmanager-0.14.0.linux-amd64/amtool` which was:
`Checking '/usr/local/example.yml'  SUCCESS`

**What did you see instead? Under which circumstances?**
Instead, the output was: 

```
Checking '/usr/local/example.yml'amtool: error: failed to validate 1 file(s)
  FAILED: yaml: unmarshal errors:
  line 22: key "firing" already set in map
```

**Environment**

* Alertmanager version:

	alertmanager, version 0.15.0 (branch: HEAD, revision: 462c969d85cf1a473587754d55e4a3c4a2abc63c)

* Alertmanager configuration file:
```
global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'

route:
  receiver: 'pagerduty-receiver'
  group_by: ['alertname', 'cluster']
  group_wait: 30s
  group_interval: 5m  
  repeat_interval: 3h
  routes:
  - receiver: pagerduty-receiver
    match:
      severity: critical

receivers:
- name: 'pagerduty-receiver'
  pagerduty_configs:
  - service_key: <some_key>
    details: {
      body: 'bar',
      firing: 'foo'
    }
```

From what I can see, switching to using strict yaml unmarshalling (https://github.com/prometheus/alertmanager/pull/1318) caused this error because strict yaml unmarshalling throws an error when trying to overwrite an existing key in a map: https://github.com/go-yaml/yaml/blob/v2/decode.go#L645.

Another issue is that `details` seems to be treated as the same map in multiple `pagerduty_configs`. So if I was to add a second receiver at the end:
```
- name: 'pagerduty-receiver2'
  pagerduty_configs:
  - service_key: <some_key>
    details: {
      body: 'bar2',
      firing: 'foo2'
    }
```
The error code is then:
```
Checking '/usr/local/example.yml'  FAILED: yaml: unmarshal errors:
  line 22: key "firing" already set in map
  line 28: key "body" already set in map
  line 29: key "firing" already set in map
```
because it is attempting to overwrite `body` in the same map.

### PR DESCRIPTION
**Pull request by simonpasquier**
Closes #1451

cc @CatherineBowen @Allex1 if one of you wants to try it.

@stuartnelson3 since it is a regression, it might be a case for a v0.15.1 release. WDYT?

### CODE REVIEW

**Comment by Allex1** [comment]
@simonpasquier I've cloned your fork, built the alertmanager from this commit, tested my pd config and it's working fine. Thanks!

Waiting for a release...

**Comment by stuartnelson3** [comment]
@simonpasquier Let's get https://github.com/prometheus/alertmanager/pull/1456 merged as well, and I want to have a look at https://github.com/prometheus/alertmanager/issues/1449 also. But yeah we should get 0.15.1 out soon for this

**Comment by mxinden** [comment]
> @mxinden want to do 0.15.1?

@stuartnelson3 sure. Happy to do that.

Shall we include #1421, #1456,  #1436 and #1437 as well?

**Comment by simonpasquier** [comment]
Maybe #1447 too if it is merged soon?

**Comment by stuartnelson3** [comment]
Merged, let's go for it

**Pull request merged**
